### ISSUE TITLE
how to correctly add elements to your gitify file 

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#102]
I would like to add the fields for clientConfig in my gitify file.  So in an already running project, what are the steps to change what gitify looks for?

I added this, but got some conflicts when running Gitify extract.

 clientconfig_groups:
    class: cgGroup
    primary: label
    package: clientconfig
  clientconfig_settings:
    class: cgSetting
    primary: key

**Comment by Mark-H** [comment]
What conflicts do you get on extract?
Op 9 jun. 2015 11:30 AM schreef "Benjamin Davis" <notifications@github.com>:

**Comment by sonicpunk** [comment]
Hi Mark,

I just created a new branch, added it again to my gitify file, tested it and it worked fine.  Then I just added it back to my master.. all is well.
