### ISSUE TITLE
sh: mysqldump: command not found when running Gitify backup

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#103]

**Comment by Mark-H** [comment]
The mysqldump tool needs to be installed for the backup to work.

**Comment by sonicpunk** [comment]
Don't see any reference to this tool in the documentation.  Where do you find this?

**Comment by Mark-H** [comment]
It's a program you need to install on your computer, which I'm pretty sure is on 99% of all servers that have mysql. Try googling for the name of whatever you use for your server environment and "install mysqldump" to find instructions.

**Comment by sonicpunk** [comment]
ok, this may help: http://stackoverflow.com/questions/3268789/add-mysqldump-to-mamp-mysql-w-apache-php-on-macos-x
