### ISSUE TITLE
Installation on MODX Cloud - Anyone got it running?

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#107]
I went through the steps,  installed Gitify, Composer, ran the composer install script... changed CHMOD.

From within my Gitify folder, the terminal tells me that Gitify is not found.
Here is my file structure:
![screen shot 2015-06-12 at 10 23 51](https://cloud.githubusercontent.com/assets/447453/8126261/31115966-10ed-11e5-8b58-68d2e0b12a74.png)

Anyone have a tip?

**Comment by studiorepublic** [comment]
If you haven't added Gitify to your path, then sometimes you need to user ./Gitify rather than Gitify to execute it. Have you tried that?

**Comment by sonicpunk** [comment]
yes, I get the following -ash: ./Gitify not found

**Comment by Mark-H** [comment]
After chatting with the lovely Elizabeth, this is an environment specific issue on the particular Cloud instance you're using. 

The workaround is to edit the Gitify file, and to change the first line to `#!/bin/php` instead of `#!/usr/bin/env php`. That's not very portable, so I wont be making that change to Gitify, but at least it gets you up and running ;)

This probably isn't an issue on the regular cloud servers.

**Comment by sonicpunk** [comment]
On a regular cloud instance, - the Amsterdam server I also needed to make this edit to the Gitify file

**Comment by sonicpunk** [comment]
So I got Gitify running on MODX Cloud except when I type in Gitify --help, I get the following error:
Fatal error: Call to undefined function Symfony\Component\Console\Descriptor\json_encode() in /www/Gitify/vendor/symfony/console/Symfony/Component/Console/Descriptor/TextDescriptor.php on line 238

**Comment by sonicpunk** [comment]
Also instead of running composer install, I needed to run it this way $ php composer.phar install

**Comment by sonicpunk** [comment]
and when I use Gitify build, I get the following error:
Fatal error: Class 'PDO' not found in /www/core/xpdo/xpdo.class.php on line 3041

**Comment by sonicpunk** [comment]
It turns out it was a cloud problem.  I have create the following path for people to follow in case they wish to run Gitify on the cloud:
1) run git clone of gitify in the www folder: $ git clone https://github.com/modmore/Gitify.git Gitify
2) install composer inside of the new Gitify folder: curl -sS https://getcomposer.org/installer | php
3) $ php composer.phar install  - install the dependencies needed for Gitify
4) $ chmod +x Gitify
5) if needed, change the php path in the Gitify/Gitify file - #!/bin/php
6) make Gitify global - open the profile: vi ~/.profile
7) press i to edit
8) add path to Gitify export PATH:/www/Gitify/:$PATH - you can find it under home/.profile
9) restart the .profile file: . .profile

**Comment by ajilderda** [comment]
Thanks for the steps @sonicpunk! There's a typo in step 8:
`PATH:/www/Gitify/:$PATH` should be `PATH=/www/Gitify/:$PATH`.

**Comment by sonicpunk** [comment]
Thanks @ajilderda I edited my comment above

**Comment by ajilderda** [comment]
The same steps as above, but a bit easier to copy paste for us lazy people. Ssh-login to your MODX Cloud instance:
```
cd www
git clone https://github.com/modmore/Gitify.git Gitify
cd Gitify
curl -sS https://getcomposer.org/installer | php
php composer.phar install
chmod +x Gitify
nano Gitify
```
change first line from `#!/usr/bin/env php` to `#!/bin/php`
`nano ~/.profile`
add `PATH=/www/Gitify/:$PATH`
```
source ~/.profile
cd ..
Gitify```

**Comment by claytonk** [comment]
UPDATE: The following is no longer necessary and will break Gitify (at least it did on my cloud instance)

> change first line from #!/usr/bin/env php to #!/bin/php

Seems to work fine with the first line left as is
