### ISSUE TITLE
Make package list part of extract and build

### ISSUE THREAD

**Issue by vguna** [modmore/Gitify#108]
Hi.

i've seen that in the latest version, Gitify is also capable of extracting installed packages from an installed modx version during init. This is really a great feature and a step forward to completely build a modx instance from SCM.

It would be great, if that function would be part of the general extract/build process so it behaves the same like for snippets, chunks etc.

I'm currently setting up a build process, where I have different environments like dev, qa, prod and I would like to use Gitify to "merge" changes from, let's say dev to qa. That means someone works with the dev modx version and adds some packages to it via manager, configures them right, adds it to pages etc. Then, when it's done, calling Gitify to extract that changes to the SCM. After adding additional features, it's time to merge the changes to qa. So the merge is done via SCM to the qa branch. Here I would like to rollout the changes to a modx installation - maybe an existing one. So simply calling Gitify build should do the trick.

Currently I would have to call Gitify init somehow on the existing dev modx instance to extract package information to the .gitify file, and use Gitify package:install --all in the qa environment.
But that is quite difficult because of the existing .gitify file and the q&a that Gitify performs on init.
An alternative is to manually extend the .gitify file for the new packages - but that could be error prone.

What do you think?

**Comment by Mark-H** [comment]
I think that makes complete sense and would be great improvement to get into 1.0.

**Comment by vguna** [comment]
Great :)!

**Comment by studiorepublic** [comment]
Would this update the .gitify file? I currently re-run Gitify init to rebuild the list of packages - automaticall updating the package section would be awesome

**Comment by vguna** [comment]
Yes, that would be the idea - at least what I was thinking about ;).
