### ISSUE TITLE
Package function should work with signatures per default

### ISSUE THREAD

**Issue by vguna** [modmore/Gitify#109]
I took a look at the current package handling where the installed packages are extracted on init and installed again when using package:install --all.

It seems that on init, only the signature name without the version is written to the gitify file. Later, on installation, this name is used to lookup the package using the "query" function of the package manager REST API. Since the signature name doesn't seem to be part of the query targeted fields, it can happen, that the package isn't found and installation fails. Example:

package name: TinyMCE Rich Text Editor
signature: tinymcerte-1.0.0-beta
gitify saved package name: tinymcerte

Query doesn't return anything using the saved package name. Instead, searching for the signature via "signature" query parameter works as expected.

IMHO, "extracting" of the packages should use the full signature to be able to install exactly that version on package-install. Not any other version. But specifying a fuzzy package name on cmdline should still be possible where the user can select from. In my usecase I use gitify to make an exact copy of an existing modx installation to get it from e.g. DEV to QA. In this case I don't want that any of the package versions should change. Therefore it would be nice if on automatic extract and installation the versions should be kept as-is.

I've implemented that functionality in my own fork that works like this:
- use full signatures on extract and install
- packages can still be specified on cmdline
- first it tries to get an exact match via signature
- if that fails, it searches again via query parameter

You can take a look at the changes here:

https://github.com/modmore/Gitify/compare/master...vguna:auto_package_handling_fix

If you're interested I can generate a pull request for that.
What do you think?

**Comment by Mark-H** [comment]
A pull request sounds great ;)

How does this change what's stored in the .gitify file, and is there any impact for existing projects that you can think of?

**Comment by vguna** [comment]
With the changes, from now on it will store the complete signature in the .gitify on init. Before, only the packagename was extracted from the signature and stored in the .gitify.

The rest should behave as before. The good thing: the package lookup is now performed in two steps - no matter whether the packagename comes from the .gitify or from the cmdline.

If it finds an exact match by signature, it will take it. If no match was found via signature, it performs the usually query as before with possible multiple matches the user can choose from.

Old .gitify entries will behave as before - because the package-only name won't match any signature. So it would perform the query as before.

I will create the pull request so you can take a look :).
