### ISSUE TITLE
Gitify build --force does not clean the database properly

### ISSUE THREAD

**Issue by pepimpepa** [modmore/Gitify#111]
Hi,

Gitify build --force does not clean up the TVs (table: modx_site_tmplvar_contentvalues maybe also other tables). Or is it possible to set up via .gitify?

Josef

**Comment by Mark-H** [comment]
Hmmm it would be possible to add this via the `truncate_on_force` option, but I wonder if resources should automatically do that because they also automatically load the TV values..

**Comment by Mark-H** [comment]
Added the truncate on force option by default to the content
