### ISSUE TITLE
Question about excluding keys

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#112]
If I have some context settings over various contexts, for example site_url that I do not want Gitify to watch, how do I write this in the .gitify file?

**Comment by sonicpunk** [comment]
Like this?
context_settings:
    class: modContextSetting
    primary: [context_key, key]
    exclude_keys:
      - editedon
      - site_url
      - base_url
      - http_host

**Comment by sonicpunk** [comment]
When I edit my .gitify file to include these exclude_keys and run Gitify extract, the ones that are excluded still get written to my gitify directory

**Comment by Mark-H** [comment]
The name might be confusing when used for settings, but `exclude_keys` excludes data from a specific object. So like the `editedon` in your example, it wont include the editedon value for each context setting into the generated file. 

What you're looking for is `where`:

```
context_settings:
class: modContextSetting
primary: [context_key, key]
exclude_keys:
- editedon
where:
   - 'key:NOT IN':
     - 'site_url'
     - 'base_url'
     - 'http_host'
```

**Comment by sonicpunk** [comment]
Excellent!  Just what I needed!!

**Comment by sonicpunk** [comment]
Hi Mark,
I have the npm watch script from Christian running, whereby when there are changes locally, Gitify build gets automatically called.  When I left out those context settings, made changes, in modx, then ran Gitify extract... afterward the build script runs... and the result is that my context settings no longer being watched - site_url and http_host, get deleted.  The expected result would be that Gitify just ignores them.

**Comment by hugopeek** [comment]
Can I ask something related here still? I want to exclude keys with a NOT LIKE condition instead of NOT IN, but that doesn't seem to work..

```
    chunks:
        class: modChunk
        primary: name
        where:
            'static_file:NOT LIKE':
                - '[[++patternlab.core_path]]%'
```

Am I doing something wrong, or is this just not possible?
