### ISSUE TITLE
Gitify Extract overrides /content/web/*.html file when same Resource Alias

### ISSUE THREAD

**Issue by studiovlijmscherp** [modmore/Gitify#113]
When duplicate Resource Aliases exist, they get overwritten (or not created?).

Example:

ResourceA.html
-- child1.html
-- child2.html

ResourceB.html
-- child1.html
-- child2.html

child1.html + child2.html are created only once.

**Comment by Mark-H** [comment]
Can you try building the content with the verbose option and share the output? `Gitify build content --verbose`

**Comment by studiovlijmscherp** [comment]
Sure, but the problem isn't the build (i think), but the extract. I'm missing resources in /content/web/ folder so they cannot be created anyway.

---

Building modContext from contexts/...
- Updated modContext: mgr
- Updated modContext: web
Building modContextSetting from context_settings/...
- Updated modContextSetting: {"context_key":"mgr","key":"allow_tags_in_post"}
- Updated modContextSetting: {"context_key":"mgr","key":"modRequest.class"}
Building content from content/...
- Building web context...
- Updated resource from id: 11
- Updated resource from id: 20
- Updated resource from id: 21
- Updated resource from id: 14
- Updated resource from id: 19
- Created new resource from id: 57
- Created new resource from id: 37
- Created new resource from id: 38
- Updated resource from id: 5
- Updated resource from id: 13
- Updated resource from id: 4
- Updated resource from id: 9
- Created new resource from id: 40
- Updated resource from id: 1
- Created new resource from id: 49
- Updated resource from id: 12
- Created new resource from id: 39
- Updated resource from id: 6
- Created new resource from id: 46
- Updated resource from id: 7
- Created new resource from id: 41
- Created new resource from id: 47
- Created new resource from id: 45
- Created new resource from id: 36
- Created new resource from id: 56
- Created new resource from id: 50
- Updated resource from id: 18
- Updated resource from id: 22
- Created new resource from id: 43
- Removed orphaned modResource with primary 
- Removed orphaned modResource with primary 
- Removed orphaned modResource with primary 
- Removed orphaned modResource with primary 
Building modCategory from categories/...
- Updated modCategory: Adress
- Updated modCategory: Breadcrumbs
- Updated modCategory: fastField
- Updated modCategory: FirstChildRedirect
- Updated modCategory: Gmarker
- Updated modCategory: mxManager
Building modTemplate from templates/...
- Updated modTemplate: Home
- Updated modTemplate: Vervolg
Building modTemplateVar from template_variables/...
- Updated modTemplateVar: lat
- Updated modTemplateVar: long
- Updated modTemplateVar: plaats
- Updated modTemplateVar: sidebarchunks
- Updated modTemplateVar: straat
Building modTemplateVarTemplate from template_variables_access/...
- Updated modTemplateVarTemplate: {"tmplvarid":1,"templateid":1}
- Updated modTemplateVarTemplate: {"tmplvarid":2,"templateid":1}
- Updated modTemplateVarTemplate: {"tmplvarid":3,"templateid":1}
- Updated modTemplateVarTemplate: {"tmplvarid":4,"templateid":1}
- Updated modTemplateVarTemplate: {"tmplvarid":5,"templateid":1}
Building modChunk from chunks/...
- Updated modChunk: blocks-i_need
- Updated modChunk: blocks-personalcoaching
- Created new modChunk: buttongroup-container
- Created new modChunk: buttongroup-item
- Created new modChunk: buttons-i_will
- Created new modChunk: collapsible_buttons
- Updated modChunk: cta-aanmelden
- Updated modChunk: cta-ikbenpersonaltrainer
- Updated modChunk: form-shareyourwish
- Updated modChunk: g_out
- Updated modChunk: gcheckbox
- Updated modChunk: ginfo
- Updated modChunk: gmapshead
- Updated modChunk: gmarker
- Updated modChunk: gmarkershead
- Updated modChunk: grArticleFullTpl
- Updated modChunk: gresult
- Updated modChunk: submenulinks
- Updated modChunk: wfInnerRow
- Updated modChunk: wfOuterTpl
- Updated modChunk: wfParentRow
- Updated modChunk: wfSideOuterTpl
Building modSnippet from snippets/...
- Updated modSnippet: Breadcrumbs
- Updated modSnippet: depth
- Updated modSnippet: FirstChildRedirect
- Updated modSnippet: getHTML
- Updated modSnippet: getResources
- Updated modSnippet: Glocation
- Updated modSnippet: Gmap
- Updated modSnippet: Gmarker
- Updated modSnippet: UltimateParent
- Updated modSnippet: Wayfinder
Building modPlugin from plugins/...
- Updated modPlugin: CKEditor
- Updated modPlugin: Geocoding
- Updated modPlugin: mxManager
Building modPluginEvent from plugin_events/...
- Updated modPluginEvent: {"pluginid":1,"event":"OnManagerPageInit"}
- Updated modPluginEvent: {"pluginid":3,"event":"OnManagerPageBeforeRender"}
- Updated modPluginEvent: {"pluginid":3,"event":"OnRichTextBrowserInit"}
- Updated modPluginEvent: {"pluginid":3,"event":"OnRichTextEditorInit"}
- Updated modPluginEvent: {"pluginid":3,"event":"OnRichTextEditorRegister"}
- Updated modPluginEvent: {"pluginid":4,"event":"OnDocFormSave"}
Building modEvent from events/...
- Updated modEvent: OnBeforeCacheUpdate
- Updated modEvent: OnBeforeChunkFormDelete
- Updated modEvent: OnBeforeChunkFormSave
- Updated modEvent: OnBeforeDocFormDelete
- Updated modEvent: OnBeforeDocFormSave
- Updated modEvent: OnBeforeEmptyTrash
- Updated modEvent: OnBeforeManagerLogin
- Updated modEvent: OnBeforeManagerLogout
- Updated modEvent: OnBeforeManagerPageInit
- Updated modEvent: OnBeforePluginFormDelete
- Updated modEvent: OnBeforePluginFormSave
- Updated modEvent: OnBeforeSaveWebPageCache
- Updated modEvent: OnBeforeSnipFormDelete
- Updated modEvent: OnBeforeSnipFormSave
- Updated modEvent: OnBeforeTempFormDelete
- Updated modEvent: OnBeforeTempFormSave
- Updated modEvent: OnBeforeTVFormDelete
- Updated modEvent: OnBeforeTVFormSave
- Updated modEvent: OnBeforeUserActivate
- Updated modEvent: OnBeforeUserDeactivate
- Updated modEvent: OnBeforeUserDuplicate
- Updated modEvent: OnBeforeUserFormDelete
- Updated modEvent: OnBeforeUserFormSave
- Updated modEvent: OnBeforeUserGroupFormRemove
- Updated modEvent: OnBeforeUserGroupFormSave
- Updated modEvent: OnBeforeWebLogin
- Updated modEvent: OnBeforeWebLogout
- Updated modEvent: OnCacheUpdate
- Updated modEvent: OnCategoryBeforeRemove
- Updated modEvent: OnCategoryBeforeSave
- Updated modEvent: OnCategoryRemove
- Updated modEvent: OnCategorySave
- Updated modEvent: OnChunkBeforeRemove
- Updated modEvent: OnChunkBeforeSave
- Updated modEvent: OnChunkFormDelete
- Updated modEvent: OnChunkFormPrerender
- Updated modEvent: OnChunkFormRender
- Updated modEvent: OnChunkFormSave
- Updated modEvent: OnChunkRemove
- Updated modEvent: OnChunkSave
- Updated modEvent: OnContextBeforeRemove
- Updated modEvent: OnContextBeforeSave
- Updated modEvent: OnContextFormPrerender
- Updated modEvent: OnContextFormRender
- Updated modEvent: OnContextRemove
- Updated modEvent: OnContextSave
- Updated modEvent: OnDocFormDelete
- Updated modEvent: OnDocFormPrerender
- Updated modEvent: OnDocFormRender
- Updated modEvent: OnDocFormSave
- Updated modEvent: OnDocPublished
- Updated modEvent: OnDocUnPublished
- Updated modEvent: OnElementNotFound
- Updated modEvent: OnEmptyTrash
- Updated modEvent: OnFileCreateFormPrerender
- Updated modEvent: OnFileEditFormPrerender
- Updated modEvent: OnFileManagerBeforeUpload
- Updated modEvent: OnFileManagerDirCreate
- Updated modEvent: OnFileManagerDirRemove
- Updated modEvent: OnFileManagerDirRename
- Updated modEvent: OnFileManagerFileCreate
- Updated modEvent: OnFileManagerFileRemove
- Updated modEvent: OnFileManagerFileRename
- Updated modEvent: OnFileManagerFileUpdate
- Updated modEvent: OnFileManagerMoveObject
- Updated modEvent: OnFileManagerUpload
- Updated modEvent: OnHandleRequest
- Updated modEvent: OnInitCulture
- Updated modEvent: OnLoadWebDocument
- Updated modEvent: OnLoadWebPageCache
- Updated modEvent: OnManagerAuthentication
- Updated modEvent: OnManagerLogin
- Updated modEvent: OnManagerLoginFormPrerender
- Updated modEvent: OnManagerLoginFormRender
- Updated modEvent: OnManagerLogout
- Updated modEvent: OnManagerPageAfterRender
- Updated modEvent: OnManagerPageBeforeRender
- Updated modEvent: OnManagerPageInit
- Updated modEvent: OnMediaSourceBeforeFormDelete
- Updated modEvent: OnMediaSourceBeforeFormSave
- Updated modEvent: OnMediaSourceDuplicate
- Updated modEvent: OnMediaSourceFormDelete
- Updated modEvent: OnMediaSourceFormSave
- Updated modEvent: OnMediaSourceGetProperties
- Updated modEvent: OnMODXInit
- Updated modEvent: OnPageNotFound
- Updated modEvent: OnPageUnauthorized
- Updated modEvent: OnParseDocument
- Updated modEvent: OnPluginBeforeRemove
- Updated modEvent: OnPluginBeforeSave
- Updated modEvent: OnPluginEventBeforeRemove
- Updated modEvent: OnPluginEventBeforeSave
- Updated modEvent: OnPluginEventRemove
- Updated modEvent: OnPluginEventSave
- Updated modEvent: OnPluginFormDelete
- Updated modEvent: OnPluginFormPrerender
- Updated modEvent: OnPluginFormRender
- Updated modEvent: OnPluginFormSave
- Updated modEvent: OnPluginRemove
- Updated modEvent: OnPluginSave
- Updated modEvent: OnPropertySetBeforeRemove
- Updated modEvent: OnPropertySetBeforeSave
- Updated modEvent: OnPropertySetRemove
- Updated modEvent: OnPropertySetSave
- Updated modEvent: OnResourceAddToResourceGroup
- Updated modEvent: OnResourceAutoPublish
- Updated modEvent: OnResourceBeforeSort
- Updated modEvent: OnResourceDelete
- Updated modEvent: OnResourceDuplicate
- Updated modEvent: OnResourceGroupBeforeRemove
- Updated modEvent: OnResourceGroupBeforeSave
- Updated modEvent: OnResourceGroupRemove
- Updated modEvent: OnResourceGroupSave
- Updated modEvent: OnResourceRemoveFromResourceGroup
- Updated modEvent: OnResourceSort
- Updated modEvent: OnResourceToolbarLoad
- Updated modEvent: OnResourceTVFormPrerender
- Updated modEvent: OnResourceTVFormRender
- Updated modEvent: OnResourceUndelete
- Updated modEvent: OnRichTextBrowserInit
- Updated modEvent: OnRichTextEditorInit
- Updated modEvent: OnRichTextEditorRegister
- Updated modEvent: OnSiteRefresh
- Updated modEvent: OnSiteSettingsRender
- Updated modEvent: OnSnipFormDelete
- Updated modEvent: OnSnipFormPrerender
- Updated modEvent: OnSnipFormRender
- Updated modEvent: OnSnipFormSave
- Updated modEvent: OnSnippetBeforeRemove
- Updated modEvent: OnSnippetBeforeSave
- Updated modEvent: OnSnippetRemove
- Updated modEvent: OnSnippetSave
- Updated modEvent: OnTempFormDelete
- Updated modEvent: OnTempFormPrerender
- Updated modEvent: OnTempFormRender
- Updated modEvent: OnTempFormSave
- Updated modEvent: OnTemplateBeforeRemove
- Updated modEvent: OnTemplateBeforeSave
- Updated modEvent: OnTemplateRemove
- Updated modEvent: OnTemplateSave
- Updated modEvent: OnTemplateVarBeforeRemove
- Updated modEvent: OnTemplateVarBeforeSave
- Updated modEvent: OnTemplateVarRemove
- Updated modEvent: OnTemplateVarSave
- Updated modEvent: OnTVFormDelete
- Updated modEvent: OnTVFormPrerender
- Updated modEvent: OnTVFormRender
- Updated modEvent: OnTVFormSave
- Updated modEvent: OnTVInputPropertiesList
- Updated modEvent: OnTVInputRenderList
- Updated modEvent: OnTVOutputRenderList
- Updated modEvent: OnTVOutputRenderPropertiesList
- Updated modEvent: OnUserActivate
- Updated modEvent: OnUserAddToGroup
- Updated modEvent: OnUserBeforeAddToGroup
- Updated modEvent: OnUserBeforeRemove
- Updated modEvent: OnUserBeforeRemoveFromGroup
- Updated modEvent: OnUserBeforeSave
- Updated modEvent: OnUserChangePassword
- Updated modEvent: OnUserDeactivate
- Updated modEvent: OnUserDuplicate
- Updated modEvent: OnUserFormDelete
- Updated modEvent: OnUserFormPrerender
- Updated modEvent: OnUserFormRender
- Updated modEvent: OnUserFormSave
- Updated modEvent: OnUserGroupBeforeRemove
- Updated modEvent: OnUserGroupBeforeSave
- Updated modEvent: OnUserGroupFormSave
- Updated modEvent: OnUserGroupRemove
- Updated modEvent: OnUserGroupSave
- Updated modEvent: OnUserNotFound
- Updated modEvent: OnUserRemove
- Updated modEvent: OnUserRemoveFromGroup
- Updated modEvent: OnUserSave
- Updated modEvent: OnWebAuthentication
- Updated modEvent: OnWebLogin
- Updated modEvent: OnWebLogout
- Updated modEvent: OnWebPageComplete
- Updated modEvent: OnWebPageInit
- Updated modEvent: OnWebPagePrerender
Building modNamespace from namespaces/...
- Updated modNamespace: breadcrumbs
- Updated modNamespace: ckeditor
- Updated modNamespace: core
- Updated modNamespace: fastfield
- Updated modNamespace: firstchildredirect
- Updated modNamespace: gmarker
- Updated modNamespace: mxmanager
- Updated modNamespace: ultimateparent
- Updated modNamespace: wayfinder
Building modSystemSetting from system_settings/...
- Updated modSystemSetting: access_category_enabled
- Updated modSystemSetting: access_context_enabled
- Updated modSystemSetting: access_policies_version
- Updated modSystemSetting: access_resource_group_enabled
- Updated modSystemSetting: allow_forward_across_contexts
- Updated modSystemSetting: allow_manager_login_forgot_password
- Updated modSystemSetting: allow_multiple_emails
- Updated modSystemSetting: allow_tags_in_post
- Updated modSystemSetting: archive_with
- Updated modSystemSetting: auto_check_pkg_updates_cache_expire
- Updated modSystemSetting: auto_check_pkg_updates
- Updated modSystemSetting: auto_isfolder
- Updated modSystemSetting: auto_menuindex
- Updated modSystemSetting: automatic_alias
- Updated modSystemSetting: base_help_url
- Updated modSystemSetting: blocked_minutes
- Updated modSystemSetting: cache_action_map
- Updated modSystemSetting: cache_alias_map
- Updated modSystemSetting: cache_context_settings
- Updated modSystemSetting: cache_db_expires
- Updated modSystemSetting: cache_db_session_lifetime
- Updated modSystemSetting: cache_db_session
- Updated modSystemSetting: cache_db
- Updated modSystemSetting: cache_default
- Updated modSystemSetting: cache_disabled
- Updated modSystemSetting: cache_expires
- Updated modSystemSetting: cache_format
- Updated modSystemSetting: cache_handler
- Updated modSystemSetting: cache_lang_js
- Updated modSystemSetting: cache_lexicon_topics
- Updated modSystemSetting: cache_noncore_lexicon_topics
- Updated modSystemSetting: cache_resource_expires
- Updated modSystemSetting: cache_resource
- Updated modSystemSetting: cache_scripts
- Updated modSystemSetting: cache_system_settings
- Updated modSystemSetting: ckeditor.autocorrect_dash
- Updated modSystemSetting: ckeditor.autocorrect_double_quotes
- Updated modSystemSetting: ckeditor.autocorrect_single_quotes
- Updated modSystemSetting: ckeditor.extra_plugins
- Updated modSystemSetting: ckeditor.format_tags
- Updated modSystemSetting: ckeditor.native_spellchecker
- Updated modSystemSetting: ckeditor.object_resizing
- Updated modSystemSetting: ckeditor.remove_plugins
- Updated modSystemSetting: ckeditor.skin
- Updated modSystemSetting: ckeditor.styles_set
- Updated modSystemSetting: ckeditor.toolbar_groups
- Updated modSystemSetting: ckeditor.toolbar
- Updated modSystemSetting: ckeditor.ui_color
- Updated modSystemSetting: clear_cache_refresh_trees
- Updated modSystemSetting: compress_css
- Updated modSystemSetting: compress_js_groups
- Updated modSystemSetting: compress_js_max_files
- Updated modSystemSetting: compress_js
- Updated modSystemSetting: confirm_navigation
- Updated modSystemSetting: container_suffix
- Updated modSystemSetting: context_tree_sort
- Updated modSystemSetting: context_tree_sortby
- Updated modSystemSetting: context_tree_sortdir
- Updated modSystemSetting: cultureKey
- Updated modSystemSetting: date_timezone
- Updated modSystemSetting: debug
- Updated modSystemSetting: default_content_type
- Updated modSystemSetting: default_context
- Updated modSystemSetting: default_duplicate_publish_option
- Updated modSystemSetting: default_media_source
- Updated modSystemSetting: default_per_page
- Updated modSystemSetting: default_template
- Updated modSystemSetting: editor_css_path
- Updated modSystemSetting: editor_css_selectors
- Updated modSystemSetting: emailsender
- Updated modSystemSetting: emailsubject
- Updated modSystemSetting: enable_dragdrop
- Updated modSystemSetting: enable_gravatar
- Updated modSystemSetting: error_page
- Updated modSystemSetting: failed_login_attempts
- Updated modSystemSetting: fe_editor_lang
- Updated modSystemSetting: feed_modx_news_enabled
- Updated modSystemSetting: feed_modx_news
- Updated modSystemSetting: feed_modx_security_enabled
- Updated modSystemSetting: feed_modx_security
- Updated modSystemSetting: filemanager_path_relative
- Updated modSystemSetting: filemanager_path
- Updated modSystemSetting: filemanager_url_relative
- Updated modSystemSetting: filemanager_url
- Updated modSystemSetting: forgot_login_email
- Updated modSystemSetting: form_customization_use_all_groups
- Updated modSystemSetting: forward_merge_excludes
- Updated modSystemSetting: friendly_alias_lowercase_only
- Updated modSystemSetting: friendly_alias_max_length
- Updated modSystemSetting: friendly_alias_restrict_chars_pattern
- Updated modSystemSetting: friendly_alias_restrict_chars
- Updated modSystemSetting: friendly_alias_strip_element_tags
- Updated modSystemSetting: friendly_alias_translit_class_path
- Updated modSystemSetting: friendly_alias_translit_class
- Updated modSystemSetting: friendly_alias_translit
- Updated modSystemSetting: friendly_alias_trim_chars
- Updated modSystemSetting: friendly_alias_word_delimiter
- Updated modSystemSetting: friendly_alias_word_delimiters
- Updated modSystemSetting: friendly_urls_strict
- Updated modSystemSetting: friendly_urls
- Updated modSystemSetting: global_duplicate_uri_check
- Updated modSystemSetting: gmarker.apikey
- Updated modSystemSetting: gmarker.bounds
- Updated modSystemSetting: gmarker.components
- Updated modSystemSetting: gmarker.default_height
- Updated modSystemSetting: gmarker.default_width
- Updated modSystemSetting: gmarker.formatting_string
- Updated modSystemSetting: gmarker.language
- Updated modSystemSetting: gmarker.lat_tv
- Updated modSystemSetting: gmarker.lng_tv
- Updated modSystemSetting: gmarker.region
- Updated modSystemSetting: gmarker.secure
- Updated modSystemSetting: gmarker.templates
- Updated modSystemSetting: hidemenu_default
- Updated modSystemSetting: inline_help
- Updated modSystemSetting: link_tag_scheme
- Updated modSystemSetting: locale
- Updated modSystemSetting: lock_ttl
- Updated modSystemSetting: log_level
- Updated modSystemSetting: log_target
- Updated modSystemSetting: mail_charset
- Updated modSystemSetting: mail_encoding
- Updated modSystemSetting: mail_smtp_auth
- Updated modSystemSetting: mail_smtp_helo
- Updated modSystemSetting: mail_smtp_hosts
- Updated modSystemSetting: mail_smtp_keepalive
- Updated modSystemSetting: mail_smtp_pass
- Updated modSystemSetting: mail_smtp_port
- Updated modSystemSetting: mail_smtp_prefix
- Updated modSystemSetting: mail_smtp_single_to
- Updated modSystemSetting: mail_smtp_timeout
- Updated modSystemSetting: mail_smtp_user
- Updated modSystemSetting: mail_use_smtp
- Updated modSystemSetting: manager_date_format
- Updated modSystemSetting: manager_direction
- Updated modSystemSetting: manager_favicon_url
- Updated modSystemSetting: manager_html5_cache
- Updated modSystemSetting: manager_js_cache_file_locking
- Updated modSystemSetting: manager_js_cache_max_age
- Updated modSystemSetting: manager_js_document_root
- Updated modSystemSetting: manager_js_zlib_output_compression
- Updated modSystemSetting: manager_lang_attribute
- Updated modSystemSetting: manager_language
- Updated modSystemSetting: manager_login_url_alternate
- Updated modSystemSetting: manager_theme
- Updated modSystemSetting: manager_time_format
- Updated modSystemSetting: manager_week_start
- Updated modSystemSetting: modx_browser_default_sort
- Updated modSystemSetting: modx_browser_default_viewmode
- Updated modSystemSetting: modx_charset
- Updated modSystemSetting: parser_class_path
- Updated modSystemSetting: parser_class
- Updated modSystemSetting: password_generated_length
- Updated modSystemSetting: password_min_length
- Updated modSystemSetting: phpthumb_allow_src_above_docroot
- Updated modSystemSetting: phpthumb_cache_maxage
- Updated modSystemSetting: phpthumb_cache_maxfiles
- Updated modSystemSetting: phpthumb_cache_maxsize
- Updated modSystemSetting: phpthumb_cache_source_enabled
- Updated modSystemSetting: phpthumb_document_root
- Updated modSystemSetting: phpthumb_error_bgcolor
- Updated modSystemSetting: phpthumb_error_fontsize
- Updated modSystemSetting: phpthumb_error_textcolor
- Updated modSystemSetting: phpthumb_far
- Updated modSystemSetting: phpthumb_imagemagick_path
- Updated modSystemSetting: phpthumb_nohotlink_enabled
- Updated modSystemSetting: phpthumb_nohotlink_erase_image
- Updated modSystemSetting: phpthumb_nohotlink_text_message
- Updated modSystemSetting: phpthumb_nohotlink_valid_domains
- Updated modSystemSetting: phpthumb_nooffsitelink_enabled
- Updated modSystemSetting: phpthumb_nooffsitelink_erase_image
- Updated modSystemSetting: phpthumb_nooffsitelink_require_refer
- Updated modSystemSetting: phpthumb_nooffsitelink_text_message
- Updated modSystemSetting: phpthumb_nooffsitelink_valid_domains
- Updated modSystemSetting: phpthumb_nooffsitelink_watermark_src
- Updated modSystemSetting: phpthumb_zoomcrop
- Updated modSystemSetting: principal_targets
- Updated modSystemSetting: proxy_auth_type
- Updated modSystemSetting: proxy_host
- Updated modSystemSetting: proxy_password
- Updated modSystemSetting: proxy_port
- Updated modSystemSetting: proxy_username
- Updated modSystemSetting: publish_default
- Updated modSystemSetting: rb_base_dir
- Updated modSystemSetting: rb_base_url
- Updated modSystemSetting: request_controller
- Updated modSystemSetting: request_method_strict
- Updated modSystemSetting: request_param_alias
- Updated modSystemSetting: request_param_id
- Updated modSystemSetting: resolve_hostnames
- Updated modSystemSetting: resource_tree_node_name_fallback
- Updated modSystemSetting: resource_tree_node_name
- Updated modSystemSetting: resource_tree_node_tooltip
- Updated modSystemSetting: richtext_default
- Updated modSystemSetting: search_default
- Updated modSystemSetting: server_offset_time
- Updated modSystemSetting: server_protocol
- Updated modSystemSetting: session_cookie_domain
- Updated modSystemSetting: session_cookie_httponly
- Updated modSystemSetting: session_cookie_lifetime
- Updated modSystemSetting: session_cookie_path
- Updated modSystemSetting: session_cookie_secure
- Updated modSystemSetting: session_gc_maxlifetime
- Updated modSystemSetting: session_handler_class
- Updated modSystemSetting: session_name
- Updated modSystemSetting: set_header
- Updated modSystemSetting: settings_distro
- Updated modSystemSetting: settings_version
- Updated modSystemSetting: show_tv_categories_header
- Updated modSystemSetting: signupemail_message
- Updated modSystemSetting: site_name
- Updated modSystemSetting: site_start
- Updated modSystemSetting: site_status
- Updated modSystemSetting: site_unavailable_message
- Updated modSystemSetting: site_unavailable_page
- Updated modSystemSetting: strip_image_paths
- Updated modSystemSetting: symlink_merge_fields
- Updated modSystemSetting: syncsite_default
- Updated modSystemSetting: topmenu_show_descriptions
- Updated modSystemSetting: tree_default_sort
- Updated modSystemSetting: tree_root_id
- Updated modSystemSetting: tvs_below_content
- Updated modSystemSetting: udperms_allowroot
- Updated modSystemSetting: unauthorized_page
- Updated modSystemSetting: upload_files
- Updated modSystemSetting: upload_flash
- Updated modSystemSetting: upload_images
- Updated modSystemSetting: upload_maxsize
- Updated modSystemSetting: upload_media
- Updated modSystemSetting: use_alias_path
- Updated modSystemSetting: use_browser
- Updated modSystemSetting: use_editor
- Updated modSystemSetting: use_multibyte
- Updated modSystemSetting: use_weblink_target
- Updated modSystemSetting: webpwdreminder_message
- Updated modSystemSetting: websignupemail_message
- Updated modSystemSetting: welcome_action
- Updated modSystemSetting: welcome_namespace
- Updated modSystemSetting: welcome_screen_url
- Updated modSystemSetting: welcome_screen
- Updated modSystemSetting: which_editor
- Updated modSystemSetting: which_element_editor
- Updated modSystemSetting: xhtml_urls
Building modExtensionPackage from extension_packages/...
> Skipping modExtensionPackage, _data/extension_packages does not exist.
Building modFormCustomizationSet from fc_sets/...
> Skipping modFormCustomizationSet, _data/fc_sets does not exist.
Building modFormCustomizationProfile from fc_profiles/...
> Skipping modFormCustomizationProfile, _data/fc_profiles does not exist.
Building modFormCustomizationProfileUserGroup from fc_profile_usergroups/...
> Skipping modFormCustomizationProfileUserGroup, _data/fc_profile_usergroups does not exist.
Building modActionDom from fc_action_dom/...
> Skipping modActionDom, _data/fc_action_dom does not exist.
Building modMediaSource from mediasources/...
- Updated modMediaSource: 1
Building sources.modMediaSourceElement from mediasource_elements/...
- Updated sources.modMediaSourceElement: {"source":1,"object_class":"modTemplateVar","object":1,"context_key":"web"}
- Updated sources.modMediaSourceElement: {"source":1,"object_class":"modTemplateVar","object":2,"context_key":"web"}
- Updated sources.modMediaSourceElement: {"source":1,"object_class":"modTemplateVar","object":3,"context_key":"web"}
- Updated sources.modMediaSourceElement: {"source":1,"object_class":"modTemplateVar","object":4,"context_key":"web"}
- Updated sources.modMediaSourceElement: {"source":1,"object_class":"modTemplateVar","object":5,"context_key":"web"}
Building modDashboard from dashboards/...
- Updated modDashboard: {"id":1,"name":"Default"}
Building modDashboardWidget from dashboard_widgets/...
- Updated modDashboardWidget: 1
- Updated modDashboardWidget: 2
- Updated modDashboardWidget: 3
- Updated modDashboardWidget: 4
- Updated modDashboardWidget: 5
Building modDashboardWidgetPlacement from dashboard_widget_placement/...
- Updated modDashboardWidgetPlacement: {"dashboard":1,"widget":1}
- Updated modDashboardWidgetPlacement: {"dashboard":1,"widget":2}
- Updated modDashboardWidgetPlacement: {"dashboard":1,"widget":3}
- Updated modDashboardWidgetPlacement: {"dashboard":1,"widget":4}
- Updated modDashboardWidgetPlacement: {"dashboard":1,"widget":5}
Clearing cache...
Done! Time: 3,348ms | Memory Usage: 12,51 mb | Peak Memory Usage: 14,87 mb

**Comment by studiovlijmscherp** [comment]
It seems enabling friendly urls + Use Friendly Alias Path solves the issue.
Resources are now created in their own subdirectories, so duplicates aren't overwritten.

**Comment by Mark-H** [comment]
Great! :) Maybe the alias path should be mandatory for use with Gitify, otherwise I'm not sure how to deal with duplicates.
