### ISSUE TITLE
Can not update MODX to latest version using gitify install:modx

### ISSUE THREAD

**Issue by Alroniks** [modmore/Gitify#115]
General issue in this:
```
Moving unzipped files out of temporary directory...
mv: невозможно переместить «./modx-2.3.5-pl/connectors» в «./connectors»: Каталог не пуст
mv: невозможно переместить «./modx-2.3.5-pl/core» в «./core»: Каталог не пуст
mv: невозможно переместить «./modx-2.3.5-pl/manager» в «./manager»: Каталог не пуст
Please complete following details to install MODX. Leave empty to use the [default].
```
Sorry for russian, but command `mv` can not replace existing folders. So, I gues, it should be replace by other command like rsync (but before run gitify we need show alert about required software) or by wrapping mv command by php.

**Comment by Alroniks** [comment]
I am preparing PR, so we will can discuss after I create pull request.

**Comment by Alroniks** [comment]
Related to https://github.com/modmore/Gitify/pull/116
Code in pull request can update modx now. Also fixed install command can install modx if system folders are exists.

**Comment by digitalpenguin** [comment]
Looking forward to this fix as the process described in the wiki "Installing a Gitify project" doesn't currently work.

**Comment by Alroniks** [comment]
@digitalpenguin In current code used command mv, that doesn't allow replace files if it's exists. Look my pull request 116 above.

**Comment by digitalpenguin** [comment]
Thanks Alroniks, I cloned from your branch.

**Comment by Mark-H** [comment]
Closing as #116 is merged
