### ISSUE TITLE
Gitify init -> ERROR in xPDOConnection::connect

### ISSUE THREAD

**Issue by fogshot** [modmore/Gitify#117]
When trying Gitify init in my existing MODX project I get the following error:

    2015-07-09 18:22:05] (ERROR in xPDOConnection::connect @ /Users/niebelschuetz/repositories/cisaria/core/xpdo/xpdo.class.php : 3045) SQLSTATE[HY000] [2002] No such file or directory

Connecting via mysql by hand works fine, also MODx itself is obviously able to - otherwise, the site wouldn't show.

I'm running on a local OS X machine with MAMP and php 5.6.10

**Comment by Mark-H** [comment]
This is likely due to the command line php not sharing the same mysql socket as the mamp php. See the docs: https://github.com/modmore/Gitify/wiki/1.2.-Installation-on-Mac-OS-X
