### ISSUE TITLE
Call to getClientIp() on null

### ISSUE THREAD

**Issue by valorcurse** [modmore/Gitify#122]
Hi,

I've been having problems with the **'Gitify install:package --all'** command. Whenever I execute the command I get the following error:

`PHP Fatal error:  Call to a member function getClientIp() on null in /<path to installation>/core/model/modx/rest/modrestsockclient.class.php on line 43`.

It seems to be some misconfiguration but can't seem to find the root of the problem.

Thanks

**Comment by valorcurse** [comment]
Update:
This only seems to happen when first installing the plugins with a fresh install. If I first install all plugins manually, then the command is able to update them without any problems.

Any ideas?

**Comment by valorcurse** [comment]
Closing issue. Apparently this happens when the php-curl package isn't installed on the system.
Might be worth adding a list of necessary packages somewhere in the wiki.

**Comment by christianseel** [comment]
We're having the same issue on a fresh install on a windows server. On two different machines…

**Comment by Mark-H** [comment]
Sounds like you need to enable curl on two different machines ;)
