### ISSUE TITLE
Building into different databases (feature request)

### ISSUE THREAD

**Issue by jGleitz** [modmore/Gitify#123]
I'm currently preparing my workflow to update a production server I do not have SSH access to. Using [git-ftp](https://github.com/git-ftp/git-ftp) I can nicely upload files, but I still need to update the database.

Therefore, I'd love to be able to use gitify on my local machine to build into a remote database (a different database than the one specified in `core/config/config.inc.php`).
Even better would be to be able to specify remote databases in the `.gitify` file and be able to do something like `Gitify build --target production`.

If there already is a way to achieve this using gitify, please tell me.

**Comment by Mark-H** [comment]
Sorry @jGleitz, I didn't seem to have noticed the notification for this one. 

There was an idea some time ago about adding a `--config` option so you could use a different config file, though I can't find that issue right now. That would be to me an acceptable way of implementing this. 

Other than that, I don't think shell access is too much to ask when you're dealing with multi-environment workflows ;) If you absolutely can't get SSH, you can also put a php file on the server that runs the necessary shell commands with shell_exec, and then you can trigger that php file from the browser. You risk running into page timeouts on larger sites, but it is what I used before Gitify to automatically pull in changes to a git repository with a webhook :P
