### ISSUE TITLE
'Fatal: Service temporarily unavailable' message when trying to backup/restore/build/init on a specific repo

### ISSUE THREAD

**Issue by studiorepublic** [modmore/Gitify#129]
We have a repo we've been using Gitify on for a while and it's worked perfectly, but today I pulled down and went to build and received a message:

Fatal
Service temporarily unavailable

I cannot backup, restore, build, or init a new Gitify over it, but the Gitify command does work to show available commands.

All other repos we're using Gitify on are working perfectly! Any thoughts are much appreciated!

Cheers, Tom

**Comment by Mark-H** [comment]
Never seen that one before. Did you take a look at the MODX and server error logs?

**Comment by studiorepublic** [comment]
Cheers Mark, all sorted now, it was being caused by an access denied error in MySQL and was showing in the MODX error logs.
