### ISSUE TITLE
Package:install --all fails after installing 1 package

### ISSUE THREAD

**Issue by hugopeek** [modmore/Gitify#131]
I'm having a weird issue when installing packages inside a Vagrant box. Every time I run package:install --all, it only installs 1 package. All subsequent packages fail:

Could not download package . Reason: invalid_data

So when running the below example again, it will install BreadCrumb, but Collections will fail again.

```
vagrant@scotchbox:/var/www$ gitify package:install --all
Searching modx.com for ace...
Found 1 package(s).
Package Ace 1.6.4 is already installed.
Searching modx.com for bigbrother...
Found 1 package(s).
Downloading Big Brother (1.3.0)...
Installing Big Brother...
[2015-09-17 07:43:27] (INFO @ /var/gitify/gitify) Grabbing package workspace...
[2015-09-17 07:43:27] (INFO @ /var/gitify/gitify) Workspace environment initiated, now installing package...
Searching modx.com for breadcrumb...
Found 1 package(s).
Downloading  ()...
Could not download package . Reason: invalid_data
Cannot install package breadcrumb.
Searching modx.com for collections...
Found 1 package(s).
Downloading  ()...
Could not download package . Reason: invalid_data
Cannot install package collections.
Searching modx.com for fastfield...
Found 1 package(s).
Downloading  ()...
Could not download package . Reason: invalid_data
Cannot install package fastfield.
Searching modx.com for formit...
Found 1 package(s).
Downloading  ()...
Could not download package . Reason: invalid_data
Cannot install package formit.
Searching modx.com for getcache...
Found 1 package(s).
Downloading  ()...
Could not download package . Reason: invalid_data
Cannot install package getcache.
Searching modx.com for getpage...
^Z
[4]+  Stopped                 gitify package:install --all
```

Probably unrelated, but I got these notices also on installing MODX:
https://github.com/modxcms/revolution/issues/12564

Vagrant box is this one: https://box.scotch.io/

**Comment by hugopeek** [comment]
Manually updated the modtransportprovider.class.php file by the way, to fix this issue #125.

**Comment by tyllo** [comment]
In Windows I have this problem too and *Manually updated the modtransportprovider.class.php* do not help.

**Comment by hugopeek** [comment]
Sorry, I see I was a little unclear. Manually updating the transport provider file only fixed the issue of not being able to install packages at all (#125). After fixing that, this issue still remained.

On localhost it works fine btw. Running PHP 5.4 there and 5.6 in the Vagrant box.

**Comment by graphiclunarkid** [comment]
Now that #125 has been fixed upstream (thank you!) I find I've now hit this issue too. I'm using the ubuntu/trusty64 Vagrant box.

**Comment by Mark-H** [comment]
So @tyllo sent a pull request to the MODX core repo linking back to this issue, but it's lacking information about how/why that is supposed to fix the problem. But you can try applying that patch and seeing if that is indeed the problem: https://github.com/modxcms/revolution/pull/12669

**Comment by hugopeek** [comment]
I don't know how or why, but tyllo's fix works for me. Thanks for that @tyllo!

Was getting the issue on my localhost now too.

**Comment by graphiclunarkid** [comment]
I've also tested the fix in the pull request. It works for me too :smile:

**Comment by sebastian-marinescu** [comment]
Hi @Mark-H and @tyllo isn't this pull request somehow misplaced? 
See: https://github.com/modxcms/revolution/pull/131

And also I see, this fix has been already pulled
( https://github.com/modxcms/revolution/pull/12669 )

Does anybody know when MODx 2.4.3 comes out?

**Comment by Mark-H** [comment]
@sebastian-marinescu This issue (#131) correlates with https://github.com/modxcms/revolution/pull/12669 - not sure how https://github.com/modxcms/revolution/pull/131 has anything to do with it?

**Comment by sebastian-marinescu** [comment]
Nevermind, I misread. 

I thought the PR was also inserted in https://github.com/modxcms/revolution/pull/131, 
but it was just referenced (which is still a bit odd, but okay).
