### ISSUE TITLE
Updating gave some errors

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#139]
I have a global installation of Gitify and inside of the Gitify folder I ran:
git pull

and got the following errors:
remote: Counting objects: 607, done.
remote: Total 607 (delta 59), reused 60 (delta 59), pack-reused 547
Receiving objects: 100% (607/607), 232.45 KiB | 0 bytes/s, done.
Resolving deltas: 100% (318/318), completed with 15 local objects.
From https://github.com/modmore/Gitify
   7247aac..1fa59b1  master     -> origin/master
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new tag]         v0.10.0    -> v0.10.0
Updating 7247aac..1fa59b1
error: Your local changes to the following files would be overwritten by merge:
	composer.lock
Please, commit your changes or stash them before you can merge.
Aborting

Any tips?

**Comment by Alroniks** [comment]
Just remove composer.lock or run `git checkout -- composer.lock` and then run `git pull && composer update`.

**Comment by sonicpunk** [comment]
Thanks!!!

**Comment by Mark-H** [comment]
Shouldn't that be `composer install` rather than `composer update`? I thought update rewrites the composer.lock file with new versions of the dependencies, causing the problem all over again.

**Comment by Alroniks** [comment]
Yep, you are right @Mark-H Better use `composer install`.
