### ISSUE TITLE
[Feature Request] add command package:build

### ISSUE THREAD

**Issue by carnevlu** [modmore/Gitify#141]
Hi,

it'll be nice to have a way to generate a _MODX transport package_ for a selection of elements via a gitify command.

So that we can share our code overt the Package Management of MODX.

Do you think that it'll be possible with your structure of the project?

**Comment by Alroniks** [comment]
Thank you @carnevlu for you request.
But I think gitify should do one thing - manage site on MODX with git and provide tools for deploy/backup/restore site, no more. 
Exists many tools for build transport packages that works very well. So you can use its. 
It's linux way: one tool for one area of tasks.

**Comment by Alroniks** [comment]
What do you think @Mark-H ?

**Comment by Mark-H** [comment]
I agree with Ivan, this is out of scope for Gitify. Transport packages are very different from what we're doing with Gitify so I don't see those two use cases fitting in a single tool. For packages I'd recommend looking at Git Package Management (GPM), MyComponent or just plain ol' build scripts.
