### ISSUE TITLE
Undefined offset warning in BuildCommand

### ISSUE THREAD

**Issue by inreti** [modmore/Gitify#142]
I constantly get tons of the following warning from gitify:

```php
(WARN @ /home/vagrant/Gitify/src/Command/BuildCommand.php : 407) PHP notice: Undefined offset: 1`
```

This is because of the too optimistic list assign in line 407: 

```php
list($rawData, $content) = explode(Gitify::$contentSeparator, $file);`
```
It seems that I have a lot of data files where no content is stored inside. But the list assign assumes always 2 parts as the result of the explode...
It might be better here to use an array instead, like this for example:

```php
$filedata = explode(Gitify::$contentSeparator, $file);
$rawData = $filedata[0];
$data = (isset($filedata[1]))? $filedata[1] : "";
```

**Comment by ershov-ilya** [comment]
Got the same mass warning

**Comment by Mark-H** [comment]
This has been resolved in https://github.com/modmore/Gitify/commit/cf7e3d02a56c43b417c883e61475dc8246ad4655
