### ISSUE TITLE
cp1251 encoding error?

### ISSUE THREAD

**Issue by Gliba** [modmore/Gitify#144]
On Gitify build when importing content with cp1251 character set error occurs:

[Symfony\Component\Yaml\Exception\ParseException]
  The YAML value does not appear to be valid UTF-8.

No suport for cirylic characters???

**Comment by Alroniks** [comment]
Hi @Gliba 
In which fields error ocurrs? Usually no problem with cirylic, but I don't use cp1251, because utf-8 covers all cases.

**Comment by Gliba** [comment]
Just content field. utf-8 working, but im trying to setup some old site with cp1251.

ty 4 response

**Comment by Alroniks** [comment]
I afraid best solution will be convert data of old site to utf8 and then try use gitify. Because YAML as language don't support cp1251, only Unicode http://www.yaml.org/spec/1.2/spec.html#id2771184
