### ISSUE TITLE
support "external" modx installations

### ISSUE THREAD

**Issue by vguna** [modmore/Gitify#152]
Hi.

Currently gitify expects, that it is run from a modx installation folder. It expects a .gitify file there that contains paths for _data and _backup which will be created within the modx installation folder. I've tried absolute paths in there (e.g. /something), but this seems to be ignored (slash removed).

Since my apache is running under www-data, and my SCM user is different, I don't have write access to the modx folder. So extract doesn't work in this case.

Since my .gitify and _data is within the SCM (having different revisions), I would like to execute gitify from within the working copy instead of the modx installation folder. This keeps the modx installation clean from any gitify related stuff and solves the permission problem as well.

Does this makes sense :)?

**Comment by Mark-H** [comment]
You can technically run Gitify anywhere. The only requirement is that there is a core.config.php file pointing to the MODX core path, and that the .gitify file is in the same place as well.
