### ISSUE TITLE
Gitify doesn't run on php 5.3 anymore

### ISSUE THREAD

**Issue by vguna** [modmore/Gitify#153]
Hi.

Updated to the latest Gitify version results in:

```php
PHP Parse error:  syntax error, unexpected T_USE, expecting T_FUNCTION in /home/veit/frontend/frontend_current_live_instance/target/php/src/Command/InstallModxCommand.php on line 21
```

During execution.

Used 0.9 before without problems. Should 5.3 still be supported? What's the minimum version?

**Comment by jswing-mie** [comment]
I concur.  Running 0.12.0. I would really like to see this fixed since I am not able to move from PHP 5.3

**Comment by Mark-H** [comment]
If you're unable of moving from 5.3, then you have a much bigger problem to worry about.

**Comment by Mark-H** [comment]
And indeed Gitify requires PHP 5.4 for installing and upgrading MODX because it uses a trait. The rest probably works for now, but expect the minimum version to go up in the future, not down.
