### ISSUE TITLE
Problem updating Gitify

### ISSUE THREAD

**Issue by hugopeek** [modmore/Gitify#158]
Got the following error when running composer update:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Installing kbjr/git.php (0.2.0)
    Cloning master
                                                                                                                    
  [RuntimeException]                                                                                                
  Failed to clone git@github.com:kbjr/Git.php, git was not found, check that it is installed and in your PATH env.  
  sh: git: command not found
```

Gitify is no longer working after this. I tried to fix it by removing everything, downloading composer and cloning gitify again, and running composer install.. But this results in the same error.

Git is available via PATH as usual btw, and operating without issues. Server is Apache, PHP 5.6.

**Comment by Mark-H** [comment]
You shouldn't run `composer update` - only ever `git pull` (or `git checkout version`) and `composer install` in the current way versions are distributed.

Not sure why it wouldn't find that package, haven't seen that error myself..

**Comment by hugopeek** [comment]
Ok, thanks Mark. Think I was confusing it with NPM then, where you always fire npm update to update all dependencies.. Something with too many tools.. :P

Will report back if I find out why the package can't be found, but for now this can be closed then as it's composer related.

**Comment by hugopeek** [comment]
@Mark-H I ended up removing the kbjr/Git.php package from composer.lock, and cloning it manually. 

Tried to change "reference": "master" to a hash (because all the other ones do that too) and tried adding .git to the clone URL (https://github.com/kbjr/Git.php**.git**), but that didn't help..

No idea why this happens, and why only on Skytoaster.. But fortunately it's relatively easy to circumvent.
