### ISSUE TITLE
"sh: 1: php: not found" non-standard php package used (serverpilot.io)

### ISSUE THREAD

**Issue by CircusMusic** [modmore/Gitify#162]
I'm using serverpilot.io on the server and php is not installed, instead they use their own packages (eg: php5.6-sp) 
I've tried changing the Gitify command to: #!/usr/bin/env php5.6-sp
This allows the command to be run but when I run "Gitify init" I get "sh: 1: php: not found" after it runs the modx setup.

I have also tried adding a user or global alias to my shell (alias php=php5.6-sp) and can run php scripts from the cli using "php test.php" but the modx install script still fails. With some basic tests on a php file it seems that the php exec function can't run the php alias command...

I'm aware this might not be a prevalent setup among the developers but I thought I would bring it up.

**Comment by Mark-H** [comment]
Have you tried creating a symlink /usr/bin/php pointing to the actual
executable? If you have access to do that, I think that might be your best
bet
Op 10 dec. 2015 2:12 a.m. schreef "CircusMusic" <notifications@github.com>:

**Comment by pitangaweb** [comment]
Hi,

One of my servers is using serverpilot.io and I can confirm that creating a symlink /usr/bin/php pointing to /usr/bin/php5.6-sp fixes the issue.

Thanks @Mark-H !
