### ISSUE TITLE
Gitify backup doesn't work

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/Gitify#172]
Hi MODx'rs and hi Mark, 

I don't think this is an Issue with Gitify, but I was hoping for a solution or some help here.

When entering `Gitify backup` the console says: 

```
Writing database backup to 2016-01-17-141400-W. Europe Standard Time.sql...
mysqldump: Couldn't find table: "Europe"
```

What is going wrong? 

Thanks in advance for any answer. 
With best regards,
Sebastian

**Comment by Mark-H** [comment]
Hmm that sounds like the spaces in the file name are messing up the mysqldump command. Does it work when you pass a name for the backup like `Gitify backup somenamehere`?

**Comment by sebastian-marinescu** [comment]
Hi Mark, 
yes it works if supplied with a file name. That is a good work-around for now. 
But what have I done wrong? Or is something misconfigured?

**Comment by sebastian-marinescu** [comment]
Closing in favour of #313
