### ISSUE TITLE
Install Gitify issue "Call to undefined function modmore\Gitify\..."

### ISSUE THREAD

**Issue by Jacqbus** [modmore/Gitify#173]
When i try to install Gitify as You presented in wiki's Installation section, everything is OK, but when i try to use: modx:install or install:modx i got this error:

> Call to undefined function modmore\Gitify\Mixins\curl_init() in /home/pietrof/Gitify/src/Mixins/DownloadModx.php on line 101

composer is up to date, but I have this problem anyway. I tried to install it like an half year ago in the same way, and then everything was perfect. Now i tried on 2 separate, independent servers and same result...

I don't know composer at all (im not pro at linux anyway), but i suppose theres some "translation" problem in: https://github.com/modmore/Gitify/blob/master/composer.json#L32

**Comment by Alroniks** [comment]
Looks like that `curl` or `php5-curl` extension is not installed in the system.

**Comment by Alroniks** [comment]
And could you say version of PHP in cli mode?

**Comment by Jacqbus** [comment]
Of course - i haven't installed php5-curl. I ask dumb question, before check that trivial things... Sorry for that.

And my PHP version is 5.5.9, but it doesn't matter anyway.

This "issue" can stay here for people like me.

Thanks Alroniks for quick response. :+1:
