### ISSUE TITLE
Mismatching Element Categories after build

### ISSUE THREAD

**Issue by digitalpenguin** [modmore/Gitify#175]
After building on staging server, many elements are now listed under incorrect categories.

For example my "MusicContentTemplate" was originally under Main->Music
but is now just listed under Collections.

**Comment by Mark-H** [comment]
Can you please show your .gitify file, or at least the relevant category/element bits?

**Comment by digitalpenguin** [comment]
Gitify file:
`data_directory: _data/
backup_directory: _backup/
data:
    contexts:
        class: modContext
        primary: key
    context_settings:
        class: modContextSetting
        primary:
            - context_key
            - key
    template_variables:
        class: modTemplateVar
        primary: name
    template_variables_access:
        class: modTemplateVarTemplate
        primary:
            - tmplvarid
            - templateid
    content:
        type: content
        exclude_keys:
            - editedby
            - editedon
        truncate_on_force:
            - modTemplateVarResource
    categories:
        class: modCategory
        primary: category
        truncate_on_force:
            - modCategoryClosure
    templates:
        class: modTemplate
        primary: templatename
        extension: .html
    chunks:
        class: modChunk
        primary: name
        extension: .html
    snippets:
        class: modSnippet
        primary: name
        extension: .php
    plugins:
        class: modPlugin
        primary: name
        extension: .php
    plugin_events:
        class: modPluginEvent
        primary:
            - pluginid
            - event
    events:
        class: modEvent
        primary: name
    namespaces:
        class: modNamespace
        primary: name
    system_settings:
        class: modSystemSetting
        primary: key
        exclude_keys:
            - editedon
    extension_packages:
        class: modExtensionPackage
        primary: namespace
        exclude_keys:
            - created_at
            - updated_at
    fc_sets:
        class: modFormCustomizationSet
        primary: id
    fc_profiles:
        class: modFormCustomizationProfile
        primary: id
    fc_profile_usergroups:
        class: modFormCustomizationProfileUserGroup
        primary:
            - usergroup
            - profile
    fc_action_dom:
        class: modActionDom
        primary:
            - set
            - name
    mediasources:
        class: modMediaSource
        primary: id
    mediasource_elements:
        class: sources.modMediaSourceElement
        primary:
            - source
            - object_class
            - object
            - context_key
    dashboards:
        class: modDashboard
        primary:
            - id
            - name
    dashboard_widgets:
        class: modDashboardWidget
        primary: id
    dashboard_widget_placement:
        class: modDashboardWidgetPlacement
        primary:
            - dashboard
            - widget
packages:
    modx.com:
        service_url: 'http://rest.modx.com/extras/'
        description: 'The official MODX transport facility for 3rd party components.'
        packages:
            - ace-1.6.5-pl
            - archivist-1.2.4-pl
            - bigbrother-1.3.0-pl
            - collections-3.4.1-pl
            - fastfield-1.4.0-pl
            - formit-2.2.8-pl
            - markdowneditor-1.1.0-pl
            - migx-2.9.6-pl
            - minishop2-2.2.0-pl2
            - pdotools-2.2.4-pl
            - pthumb-2.3.3-pl
            - resizer-1.0.1-pl
            - simplesearch-1.9.2-pl
            - upgrademodx-1.4.0-pl
`

**Comment by digitalpenguin** [comment]
Looking in the _data/ directory, the elements appear to have the correct categories.
So perhaps the problem is occurring during the build process. I'll try the process again and report back.

**Comment by Mark-H** [comment]
Try moving the categories before the TVs bit, that could be messing things up on a clean environment. 

An issue in the build step is likely. Try using `Gitify build --verbose` to see what it's doing in more detail, and/or `Gitify build --force` to first wipe the relevant tables clean to make sure there's no conflicts.

**Comment by digitalpenguin** [comment]
Hi Mark, what do you mean by moving the categories before the TVs?

I started again from scratch install:modx ran fine.
install:packages --all produced the following error when it tried to install minishop2:
--------------------------
[2016-02-01 01:55:18] (INFO @ ../Gitify/Gitify) Trying to install <b>pdoTools</b>. Please wait...

Fatal error: Call to a member function getObject() on a non-object in /public_html/core/packages/minishop2-2.2.0-pl2/modCategory/d12c340d640aaa19cad42879b2687ee9.resolve.setup.resolver on line 9
--------------------------
But I assume this is just because minishop tries to install pdotools and perhaps that way of doing things is incompatible with Gitify. Running install:packages -all again worked without a hitch.

**Comment by digitalpenguin** [comment]
I tried again - this time I ran install:package pdotools before running install:package --all and that corrected the error above.

The mismatching of categories is still happening though. 
I don't know the inner workings but I'm assuming this is because the installation of packages are taking the ids due to them being installed in a different order to how they were in development.

Would building before installing the packages work at all?

**Comment by digitalpenguin** [comment]
OK manually deleting everything in the cache folder fixed the issue. 
I had been just clearing the cache that had been generated from the install commands and I know the build command was attempting to clear the cache too but it wasn't enough.
In hindsight I should have compared the db tables to the gitify files.
Perhaps as a new feature, the build process could delete everything in the cache folder rather than clearing it? 

Thanks for the help :)
