### ISSUE TITLE
Gitify Documention of .gitify file

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/Gitify#177]
I'd like to see more realistic examples of xpdo-statements in the example config file.
I think I just did add some, but there should be more imho...

Like for settings, because you don't need all of them in your repository, but just the ones you've edited:

        where:
            - 'editedon:!=': '0000-00-00 00:00:00'

Or you probably only want the elements (chunks/snippets/plugins) of your Project-Category:

        where:
            - 'category:=': 9

**Comment by Mark-H** [comment]
> Like for settings, because you don't need all of them in your repository, but just the ones you've edited:

Yikes, I can see that being a bad idea. Because building cleans up stuff that isn't in the extract and doesn't match the `where`, you might accidentally remove some settings that way.

**Comment by sebastian-marinescu** [comment]
Yeah, I had issues with this altogether... Thanks for explaining why :+1: 

As I saw http://modmore.github.io/Gitify/en/config/the-gitify-file.html I think this issue is obsolete and I'll close it. But I think a link to https://rtfm.modx.com/xpdo/2.x/class-reference/xpdoquery/xpdoquery.where and to https://github.com/modmore/GitifyWatch#4-configure-the-gitify-environments would be a good complement on the Gitify-Documentation.
