### ISSUE TITLE
PHP Notice: Undefined index when installing modx 2.4.4 via Gitify

### ISSUE THREAD

**Issue by degoya** [modmore/Gitify#184]
### Summary
I get PHP Notice when installing modx 2.4.4 via Gitify.
the Notice doesn't apear when i install a modx 2.5 Version

### Step to reproduce
Gitify modx:install

### Observed behavior
PHP Notice:  Undefined index: primary in /var/www/core/xpdo/om/mysql/xpdomanager.class.php on line 462
PHP Notice:  Undefined index: unique in /var/www/core/xpdo/om/mysql/xpdomanager.class.php on line 462

installation finished and modx seems to work.

### Environment
Gitify 0.11, MODX 2.4.4, Debian Wheezy, MySQL 5.5+, PHP 5.6+, etc.

**Comment by Mark-H** [comment]
That's a bug in MODX that has been resolved in 2.5.
