### ISSUE TITLE
Would be nice if gitify could ...

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#185]
... scan what new packages have been installed during a project, notice what database tables belong to those packages, and write them into the gitify config file automatically.

**Comment by Alroniks** [comment]
@sonicpunk I am already working on it https://github.com/modmore/Gitify/pull/159
Unfortunately, but not have enough time to finish and test it

**Comment by sonicpunk** [comment]
@Alroniks That sounds great man!!!!
