### ISSUE TITLE
gitify workflow

### ISSUE THREAD

**Issue by AlexanderBukhtaty** [modmore/Gitify#191]
i can't undestand gitify workflow.
what i did wrong?
```
git clone gitify-url Gitify
cd Gitify
composer install
cd ..
Gitify/gitify install:modx 2.5.0-pl
...settings
```
ok, i can visit my site
install packages and
```
Gitify/gitify init
...settings
Gitify/gitify extract
```
some data has written on data folder!

how i can deploy current modx configuration on other host?
```
git clone gitify-url Gitify
cd Gitify
composer install
cd ..
```
copy _data and .gitify in work folder
```
Gitify/gitify build
```
after build i can see main page, but manager page response error
```
Fatal error: Call to a member function initialize() on null in D:\xampp\htdocs\work\modx\www\core\cache\includes\elements\modplugin\1.include.cache.php on line 26
```

**Comment by Alroniks** [comment]
Can you write me a direct message via Slack? Then I will able to answer your questions more in details.
Invite to modx channels you can get there http://modx.org/

**Comment by Mark-H** [comment]
Sounds like you might also need to install the packages on the other host.

**Comment by Alroniks** [comment]
@Mark-H We discussed with @AlexanderBukhtaty in Slack and I explained to him how gitify should work and how Alexander should use it, so now I am closing this issue.
