### ISSUE TITLE
Backup bag

### ISSUE THREAD

**Issue by AlexanderBukhtaty** [modmore/Gitify#192]
win 8
conemu(git bash)
```
gitify backup
```
when i try backup, it generate backup file with russian text and cant find it later when try write mysql tables.
http://prntscr.com/b8xnv3

but when
```
gitify backup someName
```
it correct did backup with someName

**Comment by Alroniks** [comment]
It's not a problem of Gitify. You should check and tune your CLI-environment for support of utf-8 encoding. Also, please check locale settings.
