### ISSUE TITLE
Hidden TVs for Babel not being saved in gitify file

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#194]
### Summary
Hidden TVs for Babel not being saved in gitify file

### Step to reproduce
Install Babel extra for multi-language functionality, and link resources over various contexts

### Observed behavior
Gitify extract does not pull the hidden TVs from the database for a resource

### Expected behavior
Gitify should allow me to sync all resource links via the Babel TV

### Environment
Gitify version: 0.12.0 , MODX version: 2.5 , Operating System: OSX,  PHP version: 5.6

**Comment by Mark-H** [comment]
I think I've seen somewhere that the Babel TV isn't attached to the template, which would make it not show up in gitify because it grabs associated TVs only. Can you check if the tv is assigned to the proper templates?

**Comment by sonicpunk** [comment]
I also don't think that it is actually attached...  How can we get it into Gitify?

**Comment by sonicpunk** [comment]
I manually linked the babel TV : babelLanguageLinks to the templates, and now they are stored in the Gitify yaml file.

**Comment by Mark-H** [comment]
Great :)
