### ISSUE TITLE
on Domain Factory Server getting error when running Gitify after successful install

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#200]
### Summary
Getting an error after the install process when executing ./Gitify

### Step to reproduce
Going through install process on a shared hosting account from Domain Factory

### Observed behavior
(08:22:54) [Gitify] ./Gitify
X-Powered-By: PHP/4.4.9
Content-type: text/html

<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/kunden/500402_80799/Gitify/Gitify</b> on line <b>13</b><br />

### Expected behavior
Gitify should run

### Environment
Gitify version: latest, MODX 2.5, Operating System Apache,

PHP 5.4.45 (cgi-fcgi) (built: Dec  8 2015 10:51:05)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by sonicpunk** [comment]
It seems that even though the command line is running 5.4.45, when you run ./Gitify it runs an older version of PHP? 4.4.9

**Comment by sonicpunk** [comment]
I found the solution on the Domain Factory Forum

Hab eine andere Lösung gefunden. Weiss nicht ob das eine Gute Idee ist.

1.) Ein Lokales bin Verzeichnis erstellen:
Code:
mkdir ~/bin
cd ~/bin
2.) Symlink dort drin auf PHP5
Code:
ln -s /usr/local/bin/php5-55STABLE-CLI ./php
3.) In der .bashrc ~/bin in $PATH exportieren
Code:
export PATH=~/bin/:$PATH

**Comment by Mark-H** [comment]
PHP 4.4.9? 😱
