### ISSUE TITLE
question about extension_packages

### ISSUE THREAD

**Issue by tjventurini** [modmore/Gitify#208]
I would like to know why it is important to use the extension_packages block in the .gitify file. I don't remember to have read something about it in the wiki.

Can you explain that to me pls? @Mark-H

**Comment by Mark-H** [comment]
Who told you that was important? :P

**Comment by tjventurini** [comment]
Hmm... good question :laughing: I simply thought so because it is in the default `.gitify` file.

But I would still like some info about it. Until now I haven't used it.

**Comment by Mark-H** [comment]
Doesn't look like it's in the default anymore. Maybe it was in the past, I didn't check.

One reason you might choose to ignore it is because it contains paths that may be different between environments.

**Comment by tjventurini** [comment]
Hmm... :thinking: ... I think I'm going to remove this section, simply because I'm not missing it right now.

Ok, then thanks for the info :+1:
