### ISSUE TITLE
extract content types (js, html, pdf, etc)

### ISSUE THREAD

**Issue by tjventurini** [modmore/Gitify#209]
I would like to know how to include content types defined in modx into my gitify export.

For example we are now using / instead of .html for Resources. Now I would like to include these type of settings to.

Thanks already :)

**Comment by wuuti** [comment]
Just add 
```
content_types:
    class: modContentType
    primary: [id,name]
```
to your gitify file and then extract. Should include then your content types in the export.

**Comment by tjventurini** [comment]
thanks :smile:
