### ISSUE TITLE
When resource does not have an alias in the database, Gitify does not register it

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#213]
### Summary
Converting old MODX Revolution Site from 2010 to latest MODX.  Used Gitify to extract the resources and realized that many of the resources were not written to the data folder.

In the database I saw that the alias and uri fields were empty.  It seems that older MODX Revolution versions did not require those fields.

Is there a way in the gitify config file to take care of this edge case?

**Comment by Mark-H** [comment]
> Is there a way in the gitify config file to take care of this edge case?

Not if you're defining `type: 'content'` like you should. If you were to use `class: 'modResource'` you could set a different primary, but you'll lose out on features specific to resources (like tv handling).

**Comment by sonicpunk** [comment]
Ok.  Then I will have to take care of this another way.  Thanks!
