### ISSUE TITLE
sh: mysqldump: command not found

### ISSUE THREAD

**Issue by Lefthandmedia** [modmore/Gitify#220]
### Summary
Installed Gitify on existing project, ran Gitify init 

### Step to reproduce
I wouldn't know how to reproduce

### Observed behavior
After running backup i get this.
`Brecker:dist ralph$ Gitify backup
Writing database backup to 2017-12-15T133517+0000.sql...
sh: mysqldump: command not found`

### Expected behavior
To make the backup

### Environment
Gitify version 0.12.0, MODX version 2.6.0, Operating System OSX, MySQL version 5.6.35, PHP version 7 , running on MAMP pro.

**Comment by Alroniks** [comment]
You just have to install mysqldump program. Usually, it should be installed with MySQL.

**Comment by Alroniks** [comment]
This link should help to configure your environment properly https://stackoverflow.com/questions/3268789/add-mysqldump-to-mamp-mysql-w-apache-php-on-macos-x

**Comment by Lefthandmedia** [comment]
Tnx that worked
