### ISSUE TITLE
unjustly : No MODX installation found in the current directory on Gitify init

### ISSUE THREAD

**Issue by Lefthandmedia** [modmore/Gitify#221]
### Summary
I'm getting this on Gitify init
`Warning: file_put_contents(/Users/ralph/.gitify): failed to open stream: Is a directory in /Volumes/Data/GIT-repos/Gitify/src/Command/InitCommand.php on line 302
Gitify Project initiated and .gitify file written.
No MODX installation found in the current directory. Would you like to install the latest stable version? (Y/N)  `

But there IS a modx installation in that folder.
I'm running Gitify in the '/dist' folder of my project. The .git folder is in the root of my project

### Step to reproduce
Don't know

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
Gitify version, MODX version 2.6.0, Operating System OSX, MySQL version 5.6.35, PHP version 7,

**Comment by Alroniks** [comment]
You should run gitify inside the folder with MODX sources (and place .gitify configuration in the same folder), it doesn't depend on .git directory.

**Comment by Lefthandmedia** [comment]
That is exactly where i have it. stil it thinks there is no modx installation??

**Comment by Alroniks** [comment]
Could you share your directory structure for this project? Difficult to understand the issue without real view.

**Comment by Mark-H** [comment]
It should be looking for a `config.core.php` file to determine if there's a MODX installation, make sure you have that on the same level.

**Comment by Lefthandmedia** [comment]
![phpstorm-eapscreensnapz001](https://user-images.githubusercontent.com/3350108/34102586-01f15d8e-e3ea-11e7-92b8-38bf332000b2.png)
its realy there

**Comment by Lefthandmedia** [comment]
Ok when i do Gitify init (with overwrite by now ) i get this
![path finderscreensnapz001](https://user-images.githubusercontent.com/3350108/34102855-ecc569fe-e3ea-11e7-9ddd-4d6a66c8a312.png)

After that i try to make my first extract and the results in nothing. there is nothing in my _data folder and as you see 0 records are extracted
![path finderscreensnapz002](https://user-images.githubusercontent.com/3350108/34102899-0a22ea4e-e3eb-11e7-995e-4756e159ada6.png)

**Comment by hugopeek** [comment]
Does Gitify have write permissions in the _data folder?

And do you have other installs in the same environment that use gitify
without issues?

**Comment by Lefthandmedia** [comment]
I wouldnt know. how would i give Gitify permissions? Gitify created the _data folder so i assumed it would have permission.

No not yet this is my first try with Gitify

**Comment by hugopeek** [comment]
Hmm, yeah Gitify couldn't have created the folder without write permissions.

Is your MODX install working as expected? In other words: everything
properly configured in core/config/config.inc.php?
And did Gitify install without errors?

**Comment by Lefthandmedia** [comment]
Well as far as i can see yes. It's an inherited modx install so i'm not to familiar with all the code. But the manager works

**Comment by hugopeek** [comment]
Hmm, I see. To confirm that Gitify is working properly, maybe you can
create a separate project in a different folder and run:

Gitify modx:install
Gitify init
Gitify extract

**Comment by Lefthandmedia** [comment]
on a fresh install like you suggested i get this in Gitify init
Fatal error: Class 'xPDODriver_' not found in /Volumes/Data/GIT-repos/TEST/core/xpdo/xpdo.class.php on line 1884

**Comment by Lefthandmedia** [comment]
After running Gitify modx:install and then Gitify init. i got an error about xpdo class (see above). 

So i ran the setup manualy and the manager works and the test site works.
and ran Gitify init again. now i get these errors:
> [2017-12-18 15:44:14] (ERROR in xPDOConnection::connect @ /Volumes/Data/GIT-repos/TEST/core/xpdo/xpdo.class.php : 3116) SQLSTATE[HY000] [2002] No such file or directory
[2017-12-18 15:44:14] (ERROR @ /Volumes/Data/GIT-repos/TEST/core/xpdo/om/xpdoquery.class.php : 653) Could not construct or prepare query because it is invalid or could not connect: SELECT `modTransportProvider`.`id` AS `modTransportProvider_id`, `modTransportProvider`.`name` AS `modTransportProvider_name`, `modTransportProvider`.`description` AS `modTransportProvider_description`, `modTransportProvider`.`service_url` AS `modTransportProvider_service_url`, `modTransportProvider`.`username` AS `modTransportProvider_username`, `modTransportProvider`.`api_key` AS `modTransportProvider_api_key`, `modTransportProvider`.`created` AS `modTransportProvider_created`, `modTransportProvider`.`updated` AS `modTransportProvider_updated`, `modTransportProvider`.`active` AS `modTransportProvider_active`, `modTransportProvider`.`priority` AS `modTransportProvider_priority`, `modTransportProvider`.`properties` AS `modTransportProvider_properties` FROM `modx_transport_providers` AS `modTransportProvider` 

Maybe its nothing aso i try  'Gitify extract' and i get a lot of errors. here 2 examples:

> [2017-12-18 15:45:49] (ERROR in xPDOConnection::connect @ /Volumes/Data/GIT-repos/TEST/core/xpdo/xpdo.class.php : 3116) SQLSTATE[HY000] [2002] No such file or directory
[2017-12-18 15:45:49] (ERROR @ /Volumes/Data/GIT-repos/TEST/core/xpdo/om/xpdoquery.class.php : 653) Could not construct or prepare query because it is invalid or could not connect: SELECT COUNT(DISTINCT `modContext`.`key`) FROM `modx_context` AS `modContext` 
Extracting modContext into contexts (0 records)...

Does this make sense?
RDG

**Comment by hugopeek** [comment]
Looks like something is wrong with your environment. Can you find your
phpinfo() page and see if pdo_mysql is installed properly? You can reach
this page from inside the manager too somehow, iirc..

And do you see any errors in the regular MODX log?

**Comment by Lefthandmedia** [comment]
It is a MAMP on a local OSX machine, and pdo_mysql is installed with MAMP. Modx seems to work just fine and i can work in the manager. I think somehow Gitify cant reach the database
`SQLSTATE[HY000] [2002] No such file or directory`
Gitify cant create the database properly, had to do that by hand.

**Comment by Mark-H** [comment]
The php version used on the command line might be different from the one mamp uses. That will cause it to be unable of accessing or installing a database in mamp.

**Comment by Mark-H** [comment]
https://docs.modmore.com/en/Open_Source/Gitify/Installation/Mac.html
