### ISSUE TITLE
Does Gitify work with advanced installation

### ISSUE THREAD

**Issue by travisbotello** [modmore/Gitify#224]
Quick question here: Does Gitify work with MODx advanced installation?

**Comment by Mark-H** [comment]
Define "work"?

**Comment by travisbotello** [comment]
I mean in general: 

1. Is it possible to use Gitify with an advanced installation of MODx? (Setup with custom config, connectors and manager names) 
2. Can I install an advanced installation of MODx using `Gitify install:modx`

**Comment by Realetive** [comment]
@travisbotello I have old fork with this feature: https://github.com/modmore/Gitify/compare/master...Realetive:advanced-installation?expand=1

**Comment by Mark-H** [comment]
1) Yes, gitify will work with any MODX setup as long as it can find the core through a config.core.php
2) No, but @Realetive's fork may help with that, and #223 or #219 look like potential solutions, too.
3) That _should_ work? Can't say I've tried recently

**Comment by travisbotello** [comment]
Thanks @Realetive I will check it out. Also @Mark-H these two pull requests look very promising.
