### ISSUE TITLE
latest tag is broken?

### ISSUE THREAD

**Issue by zeves095** [modmore/Gitify#229]
### Summary
broken tag "latest" when gitify modx:install

### Step to reproduce
./Gitify/gitify modx:install
Looking up latest MODX version...
Latest version: latest
Downloading modx-latest from https://modx.s3.amazonaws.com/releases/2.6.2/modx-2.6.2-pl.zip...
######################################################################## 100.0%
Extracting package...
cp: cannot stat '/root/.gitify/modx-latest/*': No such file or directory
Please complete following details to install MODX. Leave empty to use the [default].
Database Host [localhost]: ...
...
Manager Email: ...
Running MODX Setup...
Could not open input file: /site_home_folder/setup/index.php
Done! Time: 71,569ms | Memory Usage: 1.74 mb | Peak Memory Usage: 1.77 mb

### Observed behavior
nothing was installed. directory still empty.

### Expected behavior
installed modx with core/  connectors/ .. folders

### Environment
Gitify version: 0.12.0, 
MODX version: latest, 
Operating System: Linux Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux, 
MySQL Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper 
PHP version PHP 7.1.1 (cli) (built: Jan 24 2017 18:37:20) ( NTS )

----------
and all this inside docker containers..

and also - when i use: ./Gitify/gitify modx:install 2.6.2-pl - it's all OK (with exact version)

**Comment by Mark-H** [comment]
Sometimes "latest" doesn't resolve to a version number because of connection issues, not really something we can address I think, other then maybe increasing the timeout. I think that may be what happened here.
