### ISSUE TITLE
Incorrect feedback: Removed orphaned object with primary Array

### ISSUE THREAD

**Issue by hugopeek** [modmore/Gitify#231]
### Summary

When running Gitify build, the output doesn't show which orphaned objects are removed if primary key is an array.

### Step to reproduce

Delete some random data files of objects that have multiple primary keys and `Gitify build`.

### Observed behavior

So when your config is something like:
```
    cb_fields:
        class: cbField
        primary:
            - id
            - name
```

the output will be:
```
Building cbField from cb_fields/...
- Removed orphaned cbField with primary Array
- Removed orphaned cbField with primary Array
- Removed orphaned cbField with primary Array
- Removed orphaned cbField with primary Array
- Removed orphaned cbField with primary Array
```

### Expected behavior
Correct output should be something like:

```
Building modPlugin from plugins/...
- Removed orphaned modPlugin with primary Collections
- Removed orphaned modPlugin with primary Ace
- Removed orphaned modPlugin with primary FormIt
- Removed orphaned modPlugin with primary ClientConfig
- Removed orphaned modPlugin with primary ImagePlus
- Removed orphaned modPlugin with primary ContentBlocks

```

### Environment
Gitify 0.12.0
MODX 2.5.8
PHP 7.1

**Comment by Mark-H** [comment]
As is being done elsewhere I believe, the primary should be `json_encode` if it's an array.

**Comment by hugopeek** [comment]
Thanks Mark. Will look for that and try to create a PR.
