### ISSUE TITLE
Release on Packagist.org

### ISSUE THREAD

**Issue by jgulledge19** [modmore/Gitify#234]
### Summary
Release on Packagist.org

### Step to reproduce
N/A

### Observed behavior
N/A

### Expected behavior
Install via composer

### Environment
PHP 7+

**Comment by jgulledge19** [comment]
Related #232

**Comment by JoshuaLuckers** [comment]
@Mark-H would it be possible to publish Gitify on Packagist? 
This will also partially solve #232.

**Comment by Mark-H** [comment]
This has been done with the new v2. That's currently in alpha. See the readme for updated installation instructions.
