### ISSUE TITLE
Gitify backup fails do to user permission

### ISSUE THREAD

**Issue by jxarms3** [modmore/Gitify#235]
### Summary
mysqldump: Got error: 1044: Access denied for user 'user'@'localhost' to database 'db_name' when using LOCK TABLES....How can I change the db user so that the backup will succeed? Is this a modx thing or a gitify thing

### Step to reproduce
run: Gitify backup

### Observed behavior
see summary

### Expected behavior
backup

### Environment
Gitify version, MODX version, Operating System, MySQL version, PHP version, etc.

**Comment by jxarms3** [comment]
this was resolved by putting my root user/pass in config.inc.php... is there a better way?

**Comment by hugopeek** [comment]
That's a server thing. I think it's better to check your MySQL permissions
first, to see if the local user is allowed to perform all database actions.

If it's a live environment, using root to access the database is not a good
idea. If the site gets compromised, an attacker might gain full access to
your entire DB that way.

**Comment by Mark-H** [comment]
Yeah, sounds like you just need to make sure the dbuser you used for MODX has the appropriate permissions.
