### ISSUE TITLE
Property Set support

### ISSUE THREAD

**Issue by watou** [modmore/Gitify#249]
### Summary
I extracted my MODX site and can find no evidence of a named property set's contents in the files output (manager URI /manager/?a=element/propertyset).  Are MODX sites that use Property Sets not good candidates to use with Gitify, or have I just managed to miss where Property Sets are saved in the extracted files output?

### Environment
Gitify version 0.12.0, MODX version 2.6.5, Operating System macOS Mojave, MySQL version 5.6.38, PHP version 7.2.1

**Comment by Mark-H** [comment]
You'll need to add property sets to your .gitify configuration file. I believe the class name you're looking for is `modPropertySet` but there may also be additional joining tables you'll need to extract.
