### ISSUE TITLE
Option to ignore a data type

### ISSUE THREAD

**Issue by adamwintle** [modmore/Gitify#26]
When running an extract it could be useful to have a flag ignore or not extract some of the data for that particular extraction. e.g. gitify extract -content

Could later be expanded/more advanced e.g. gitify extract -contexts contextname which would then ignore that context, plus its content; or gitify extract -categories categoryname, and all elements inside that category are not extracted

**Comment by isaacniebeling** [comment]
Why not both? `Gitify extract -snippets` does everything except snippets; `Gitify extract snippets` does only snippets.

**Comment by Mark-H** [comment]
Things like `-v`are shorthand for CLI options/flags, so that could get confusing/messy in the code. Also I think it's more likely you've just changed one thing and want to extract that, compared to wanting to extract everything except one thing.

**Comment by isaacniebeling** [comment]
> Things like -vare shorthand for CLI options/flags

True.

> Also I think it's more likely you've just changed one thing and want to extract that

That may be true, but I can think of a lot of situations where you might want a couple of things but not others; maybe `--exclude snippets` would be better

**Comment by Alroniks** [comment]
I suggest this variant:
```
gitify build --exclude snippets chunks template
gitify build --only snippets chunks
```
Also for extracting:
```
gitify extract --exclude snippets chunks template
gitify extract --only snippets chunks
```

**Comment by Alroniks** [comment]
:cry: Cymfony Console not allow syntax --only something something etc. We need use --only="snippets,chunks"

**Comment by Mark-H** [comment]
`Gitify extract templates chunks snippets` works as of 0.8 (or current master), as does `Gitify build templates chunks snippets`. I've opened #79 to track the feature of excluding certain data so this one can be closed :D
