### ISSUE TITLE
Document installing on windows

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#28]
http://stackoverflow.com/questions/7307548/how-to-access-php-with-the-command-line-on-windows/7307581#7307581

common executable paths: 
```
c:\php\php.exe
c:\php5\php.exe
c:\windows\php.exe
c:\program files\php\php.exe
c:\wamp\bin\php\php5\php.exe
c:\xampp\php\php.exe
```

**Comment by sonicpunk** [comment]
Some docs here about integration with vagrant would be awesome!
