### ISSUE TITLE
error during extract moregallery/moregallery.class.php on line 556

### ISSUE THREAD

**Issue by ivndz** [modmore/Gitify#295]
### Summary
Error During extract

### Step to reproduce
From the project folder, I receive this error when I run Gitify extract.

### Observed behavior
Extracting modContext into contexts (2 records)...
Extracting modContextSetting into context_settings (2 records)...
Extracting modTemplateVar into template_variables (0 records)...
Extracting modTemplateVarTemplate into template_variables_access (0 records)...
Extracting content into content (5 resources across 1 contexts)...
- Extracting resources from web context (5 resources)...
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /home/ivan3/core/components/moregallery/model/moregallery/moregallery.class.php on line 556
### Expected behavior
How it should behave after following steps above.

### Environment
Gitify 0.12, ModX 2.7.1, CentOS 7, MySQL 5.5, PHP 7.1
Gitify version, MODX version, Operating System, MySQL version, PHP version, etc.

**Comment by Mark-H** [comment]
That error means the used PHP version is **not** PHP 7.  Try running `/usr/bin/env php --version`
 
If `php --version` gives you a different response, then that means there are multiple versions of PHP in your PATH and it might be worthwhile looking at why, and how to resolve that so the `/usr/bin/env` fetches the right one. 

(Or you can edit `Gitify` and change the first line to point to the right PHP executable.)

**Comment by ivndz** [comment]
Sayyyyy what.  You were absolutely correct. My command line php version defaulted to php5 for some reason.  

It turns out my nginx and command line version of php can be different. New info to me.

**Comment by ivndz** [comment]
Thank you for your help Mark. Everything is working great.

**Comment by Mark-H** [comment]
I totally didn't run into this myself last week.. ;)

**Comment by ivndz** [comment]
Well it caught me off guard because I have two modx sites. One with moregallery and one without (soon to be with). It worked without an issue or prompt on the first site, but then it gave me an error on the second. Same server. Thanks again.
