### ISSUE TITLE
Composer install fails because of Git.php

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/Gitify#356]
### Summary
Using `composer install --no-dev` the installation fails with the error-message: 
> Could not scan for classes inside “/opt/Gitify/vendor/kbjr/git.php/git.php” which does not appear to be a file nor a folder

( see https://forum.modmore.com/t/error-composer-install/2167/2 )

@Mark-H Git.php isn't acutally used inside Gitify anywhere, but by GitifyWatch, wasn't it?

**Comment by Mark-H** [comment]
The git instance gets created inside Gitify but afaik yes, that only gets called from gitifywatch 

https://github.com/modmore/Gitify/blob/master/src/Gitify.php#L107-L120

**Comment by sebastian-marinescu** [comment]
I'll try to look into that issue in the next weeks, but if I don't find a solution, or the maintainer of Git.php  isn't reacting, would you be open to switching to something like https://github.com/czproject/git-php ? (check out the author's name #insider)

**Comment by Mark-H** [comment]
Sure, would probably be ideal to reimplement it in Gitify Watch instead of Gitify and then just removing it from here.

**Comment by dbrumann** [comment]
I have created a quickfix that only removes the autoload section from the custom repository, which will then use autoloading defined in the external repository, where it was introduced in a recent pull request. If you have an existing installation you might have to manually remove the vendor folder first in order for the existing autoload not to be tainted.
