### ISSUE TITLE
Getting  YAML error on server but on local

### ISSUE THREAD

**Issue by ysanmiguel** [modmore/Gitify#372]
I'm running a build on a hosting and it's giving this error:

```
Symfony\Component\Yaml\Exception\ParseException]
  Malformed inline YAML string
```

The weird thing is that local server is not giving any trouble, any idea how to solve this?
Thanks!

**Comment by Mark-H** [comment]
That suggests a yaml file isn't valid - same files on both environments shouldn't have any difference in that. 

I think you'll have to find out what file it is and figure out why it's invalid...

**Comment by ysanmiguel** [comment]
@Mark-H hello mate, thanks for you r answer, not idea what was the error but we make it work at the end, thanks for your help mate, cheers!
