### ISSUE TITLE
New command: Gitify backup

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#39]
To run before doing stuff that can be potentially harmful (somewhat related to #37), Gitify backup could write a quick backup of the full database, perhaps matched with `Gitify restore <backup id>`

**Comment by adamwintle** [comment]
This sounds useful, but is it in the scope of Gitify? Couldn't the developer make a mySQL dump via the command line or GUI tool; and then also restore via MySQL if needed.

Where then would the mySQL backups then be stored; inside the _data folder (then committed to git) or somewhere else?

**Comment by degoya** [comment]
we actually do the backups by cli like adam said, but i would like to see the feature inside gitify to revert the db if something goes wrong on build.

**Comment by Alroniks** [comment]
If add 100+ command and call this as `modxer` instead `gitify` - then it can be real :)
But tools should do own work and do it very well, by linux way.

**Comment by Thunderofnl** [comment]
@Alroniks Well, it's not as simple as that. It is PART of what it should do. It should not do it like you guys are saying though. It should be done in silence when it starts the build process and only if there are any errors return anything. It shouldn't be a feature but a safety measure so when gitify breaks a site it can revert itself. So it shouldn't be added as a commando but as part of the build process.

**Comment by Mark-H** [comment]
Backup and restore have been added :) Documentation at https://github.com/modmore/Gitify/wiki/2.-Available-Commands has been updated.

The primary reason I see this as something that should be part of Gitify is, like @Thunderofnl says, it's a safety measure for when building (and in particular `Gitify build --force`). I've borked too many test sites and lost too many changes by doing a force build over the past few months that it has proven its value to me ;) Under the hood it simply uses `mysqldump` and `mysql`, but by not having to remember database details (it grabs those from the MODX config file) and the specific command, it's a lot more accessible. 

The way the backup is implemented is two fold. There's the separate commands (`Gitify backup` and `Gitify restore`) which you can run manually when you want a quick mysql dump. Secondly when doing `Gitify build --force` it will first run a `Gitify backup`. If you're absolutely sure you don't need the backup, you can add the `--no-backup` flag, but by default it will protect you from sites breaking. 

Backups are written to a directory specified in the `.gitify` file, with the new `backup_directory` option in the root. `Gitify init` includes that now as well. If it's not specified (say existing projects you upgrade to a new Gitify release), it will write the backups to a _backup folder. 

As with the _data folder, it's important that users lock down the _backup folder through htaccess or something to prevent direct access if it's in the webroot. (#59)

**Comment by Alroniks** [comment]
@Mark-H :+1: It's awesome!

**Comment by adamwintle** [comment]
We've also borked an instance two times with `Gitify build --force`, going to test this immediately :+1:
