### ISSUE TITLE
errors when installing package in MODX3

### ISSUE THREAD

**Issue by devtendenz** [modmore/Gitify#398]
### Summary
errors when installing package in MODX3

### Step to reproduce
gitify package:install pdoResources
or just
gitify package:install

### Observed behavior
It does not install the package and gives this error:
[2022-05-17 16:58:19] (WARN @ /var/www/html/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 526) Could not load package metadata for package modx.transport. Upgrade your model.
Cannot load Provider to install pdoResources

### Expected behavior
It should download and install the package

### Environment
Gitify version 2.0.0-alpha3, MODX version 3.0.1, Operating System Debian 11.3 , MySQL version 5.7.38, PHP version 8.0.19

**Comment by PZ31k0nauT** [comment]
I experienced the same. I tried different versions. I tested 2.0.0-alpha1, 2.0.0-alpha2, 2.0.0-alpha3 and 1.1.2 with MODX 3.0.0 and 3.0.1. To no avail, same error message as stated above has been shown. The installation of MODX through Gitify works fine in these cases.
With 2,8.4 package install for Gitify 2.0.0-alpha3 works fine.

Environment: Apache/2.4.38 (Debian), MySQL 5.7.35  and PHP 7.4.20

**Comment by Spheerys** [comment]
I confirm the issue with MODX3

**Comment by Mark-H** [comment]
There are some strict type checks that need to be addressed for 3.0. Thanks for reporting.

**Comment by muzzwood** [comment]
A bit more refactoring is going to be needed with this, partly due to different request objects being returned from the provider. MODX 2.x had `modRestResponse`, whereas 3.x has a PSR response object.
