### ISSUE TITLE
Build .gitify on init with support for installed packages

### ISSUE THREAD

**Issue by degoya** [modmore/Gitify#41]
it could be great to get a .gitify generated on gitify init with all settings for the actual installed packages, content and all system settings. 

a nice way would be a 

    gitify init-fullsite

**Comment by Mark-H** [comment]
You mean it would create a .gitify file based on an existing site? 

When packages are implemented (#3) maybe `Gitify init` should automatically grab the installed packages to add to the file, not sure if a whole new command is necessary for that. Unless there's extra features I'm missing.

**Comment by Mark-H** [comment]
I've implemented more recommended options for the gitify init in bbd845635e5374756cb772f3378a07c4f175d4ee, and it will now also (optionally) grab installed packages, from any  provider including their API Keys. 

It doesn't include every possible object, but I've based what it asks for on some real life projects we've been working on with Gitify, so it should be a solid set of data to include now.

**Comment by degoya** [comment]
that sounds really great, need to give it a test when i get some free minutes.
