### ISSUE TITLE
modx:install command fails

### ISSUE THREAD

**Issue by hugopeek** [modmore/Gitify#431]
### Summary

Hi all. Thanks for releasing 2.0.0-pl. Nice work! There is one problem though: the install command is broken, because it also has a --config option..

### Step to reproduce

Install 2.0.0-pl and run `gitify modx:install`

### Observed behavior

Error returned: An option named "config" already exists.  

### Expected behavior

The base config option should not interfere with the modx:install flag. Should we rename one of them? Or can we avoid collition some other way?

### Environment
Gitify 2.0.0-pl 
MODX 2.8.5
PHP 8.1

### Related

Base config option was introduced in https://github.com/modmore/Gitify/pull/417

**Comment by muzzwood** [comment]
Holy moly, that one went right past me. 🤦🏻 Thanks for spotting that so quickly @hugopeek ! 
I'll get it sorted today.

**Comment by muzzwood** [comment]
Hi @hugopeek , 2.0.1 is out now with the new base config option renamed to `--dotfile`.

**Comment by hugopeek** [comment]
Hi @muzzwood, thank you for the quick reaction! Yeah, just sheer coincidence that I was setting up a new project exactly on the day of release. That process is automated and installs Gitify per project, so I noticed soon enough :)
