### ISSUE TITLE
Installation on a windows machine

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#44]
Is there any documentation that would help windows users?  I have it installed globally, but for example ./Gitify gives me '.' is not recognized as an internal or external command, operable program or batch file.

**Comment by sonicpunk** [comment]
Just saw that there was a post about this topic.  So I guess I should install Gitify within my WAMP environment.

**Comment by Mark-H** [comment]
Here are my notes about that, please feel free to edit it with more detail:
https://github.com/modmore/Gitify/wiki/1.1.-Installation-on-Windows
Op 20 jan. 2015 11:22 schreef "Benjamin Davis" <notifications@github.com>:

**Comment by sonicpunk** [comment]
But where do you install it?  Do you need to install it in a running server environment, for instance within your root directory assigned to your WAMP installation?  Or like node.js, ruby, etc you install it globally over the whole system?

**Comment by Mark-H** [comment]
You install it globally like node and ruby. I did install it in my mamp
(=wamp for Mac) folder to have easy access to it for updating, but that's
not required. Adding it to your path is most important.
Op 20 jan. 2015 11:45 schreef "Benjamin Davis" <notifications@github.com>:

**Comment by sonicpunk** [comment]
What is considered the Gitify Executable?  The path for my php is correct and in my case I created a Gitify folder on my os hard drive C:\Gitify, and I installed it there - resulting in 2 Folders called Gitify, so C:\Gitify\Gitify.  I added that to my path but to no avail.

**Comment by sonicpunk** [comment]
Ok, if I use the command 'php Gitify', then I get the screen as stated in the installation docs.  That page that shows what version adn the Options.

**Comment by designbywilliam** [comment]
Do yourself a favour and install , for example, Scotch lamp box and use that. First of all that env will most likely be more like your production env. And second of all, you don't need to mess too much with windows.

Thats the way i run it on my pc's when i got to use em.

**Comment by sonicpunk** [comment]
I already have WAMP installed for the current project.  So if I install Gitify locally within the assigned root document in WAMP... maybe that would work???

**Comment by designbywilliam** [comment]
I have personally never used WAMP so i can not say. But why don't you try and let us know what happens.

**Comment by sonicpunk** [comment]
The Problem is that I can't get Gitify to run on the command line.  I don't think that the issue is linked to which type of webserver I am running.  I installed Git within the rootDirectory and of course it is still not running in the command line.

**Comment by Mark-H** [comment]
@sonicpunk it is definitely related to the type of webserver, because it needs to access part of the (PHP and MySQL). Windows is a bit picky in how things are set up and truthfully I've not got a whole lot experience setting Gitify up in windows. The instances I did set up, just required adding PHP and Gitify to the PATH variable as mentioned in https://github.com/modmore/Gitify/wiki/1.1.-Installation-on-Windows and the StackOverflow link contained within.

It's a bit hard to provide any worthwhile advise here when I don't fully understand your environment myself, so if the problem persists until the CCC please do bring this up so we can sit down with your laptop and figure out where it goes wrong.

**Comment by sonicpunk** [comment]
Guess I'll just buy a mac ;)

**Comment by Mark-H** [comment]
The problem here was likely the double Gitify/Gitify/ in the PATH (which was wrong in the documentation, my bad).. but given you bought a mac I'm closing this issue ;)

**Comment by hansek** [comment]
If someone needs install Gitify on Windows, try my solution http://wiki.tezner.cz/code/modx-revolution/gitify

;)
