### ISSUE TITLE
Additional params for build command

### ISSUE THREAD

**Issue by Alroniks** [modmore/Gitify#51]
When you develop site from IDE, you should everytime run `Gitify build` for apply changes to modx. But it takes time, if it's big site - a lot of time. 
By default command should build all elements from config, but we should have ability define only selected elements.
Examples:
```
Gitify build # all
Gitify build --snippets --chunks # only snippets and chunks
Gitify build --templates # build only template
Gitify build --system_settings # build only system settings
```

`--param` should be key from config

**Comment by Alroniks** [comment]
Gitify build --packages - for sync installed packages

**Comment by Mark-H** [comment]
Related to #26 

The format I have in mind would be `Gitify build snippets chunks` instead of using --flags though.

**Comment by Mark-H** [comment]
e7b0f4e33792bcc14582a93a4ca5848ed8ea8246

**Comment by Mark-H** [comment]
> Gitify build --packages - for sync installed packages

That would be `Gitify install:package --all` :)
