### ISSUE TITLE
Wrong package found and installed

### ISSUE THREAD

**Issue by Thunderofnl** [modmore/Gitify#58]
I defined `FormIt` in my `.gitify` but what happens is that gitify uses the modx search to find the package and then downloads the first returned package. The first returned package for a search of `FormIt` is `FormIt2db` so it downloads and installs the wrong package.

I've been pondering with 2 solutions:

- Define the author in the `.gitify` so the search can also check on author (Means it gets more accurate)
- Define a version although I think that's more of a different feature than the solution to this problem.

**Comment by Mark-H** [comment]
Also happens for "migx" which installs "migxMultiLang" instead. While this is in my opinion a server-side issue with the package repo,maybe the way to fix this is to simply prefer exact matches in the Gitify code. This would choose "migx" over "migxmultilang" from the result set and should also work with the formit example in this issue.

**Comment by Alroniks** [comment]
Thank you @Mark-H :+1:
