### ISSUE TITLE
[Feature request] Security of _data folder

### ISSUE THREAD

**Issue by Thunderofnl** [modmore/Gitify#59]
I have noticed that the `_data` folder is totally insecure and if someone leaves it in their live website people could go to `_data` and get all the contents.

Solutions:
- Encrypt the `_data` folder and let gitify decrypt it with the password (As a parameter)
- Let Gitify put `index.html`'s in every directory (not `.htaccess`'s because NGINX doesn't work with those)

**Comment by Thunderofnl** [comment]
Also, the same can be applied to `.gitify`

**Comment by Mark-H** [comment]
```` htaccess
# Block access to dotfiles and folder people have no need to touch
RewriteRule ^(\.|core|_data) /index.php?q=404 [L]
````

**Comment by Mark-H** [comment]
The _data directory is also configurable (and I guess in the wiki we can encourage changing it from the default), and there are similar ways of blocking access to a folder or dotfiles on nginx.

**Comment by Alroniks** [comment]
and rule for nginx:
```
location /core {
    deny all;
}
location /_data {
    deny all;
}
```

**Comment by Mark-H** [comment]
thanks @Alroniks :D

**Comment by Thunderofnl** [comment]
Ah that could work ^.^

**Comment by Mark-H** [comment]
If there's still things to discuss here, please feel free to reopen :)

**Comment by adamwintle** [comment]
We also always make our data folder called /.gitify-data/ so its hidden from the regular file system
