### ISSUE TITLE
[Feature request] install:package --all to ask if you want to install the package

### ISSUE THREAD

**Issue by Thunderofnl** [modmore/Gitify#60]
When doing `gitify install:package --all` I would like for it to ask me per package if I want to install it like it does when you do `gitify install:package NAME` and if possible then have the options `(Y)es`, `(N)o`,   `(Y)es to (A)ll` (YA) and `(N)o to (A)ll` (NA).

**Comment by Mark-H** [comment]
I think the point of the `--all` flag is to automatically install the packages you have defined that needs to be installed... If we fix #58 where it may install the wrong package, would this feature request still have value?

**Comment by Thunderofnl** [comment]
Well for me it would because we would like to use gitify for a base install and it would be cool if we could choose the packages that should be installed for a client via gitify. It's not high priority though but just something to think about.

**Comment by Alroniks** [comment]
I think for this we can add flag `--interactive` and short version `-i` 
`gitify  install:package --all --interactive`
