### ISSUE TITLE
Ability to run a MODX upgrade 

### ISSUE THREAD

**Issue by Mark-H** [modmore/Gitify#7]
The `.gitify` could contain a `modx_version` (or just `version`) key that contains the MODX version that it is expected to run. Then with a `Gitify build` or `Gitify update-modx [version]` it could grab that specific version and run the command line upgrade.

**Comment by Alroniks** [comment]
I think it can be closed, because described functions already works.

**Comment by Mark-H** [comment]
Yep, was added in #116 :)
