### ISSUE TITLE
Gitify installs migxMultiLang instead of MIGX

### ISSUE THREAD

**Issue by christianseel** [modmore/Gitify#72]
Gitify installs migxMultiLang instead of MIGX when `migx` is added to package object in `.gitify` and you run `Gitify install:package --all`.

**Comment by Mark-H** [comment]
Dupe of #58 that should have been fixed per https://github.com/modmore/Gitify/commit/47c7b905fc85c9420fe127a2f30346e1470186de... if it's still happening we can leave this open, but I specifically tested migx/migxMultiLang at the time and I recall that working?

**Comment by christianseel** [comment]
Ha! Yeah, had to update Gitify…
Through seopro+seotab still don't work, but thats an other issue.
