### ISSUE TITLE
Add modx:reinstall command

### ISSUE THREAD

**Issue by adamwintle** [modmore/Gitify#76]
It would be useful to be able to quickly reinstall the current version of MODX which is installed. Sometimes when things go wrong its best to just reinstall MODX. 

This would be different from install:modx command as reinstall:modx would not be a fresh installation.

**Comment by Alroniks** [comment]
I think this case can solve command `gitify upgrade:modx` or `gitify update:modx` with --version parameter (for reinstall specified version)

**Comment by Mark-H** [comment]
I'm going to guess from a code perspective that makes most sense, as upgrading to the same version and doing a reinstall would be the exact same process, so I agree :dancer: 

@Alroniks I noticed your `upgrade_modx` branch the other day - is that ready for testing/a pull request or does it still need a lot of work?

**Comment by Alroniks** [comment]
@Mark-H Need more tests, it's dangerous run it on working site )

**Comment by Mark-H** [comment]
Closing as modx:upgrade is now available which will do the trick
