### ISSUE TITLE
Gitify extract issues

### ISSUE THREAD

**Issue by sonicpunk** [modmore/Gitify#94]
Many times when I run Gitify extract, strange changes takes place.  For example in a template the MODX placeholders will be missing, and in my context settings, there will be some that disappear and an emtpy .yaml file will be written.

my gitify file is written so:

data_directory: _gitify/
backup_directory: _backup/
data:
  contexts:
    class: modContext
    primary: key
  context_settings:
    class: modContextSetting
    primary: [context_key, key]
    exclude_keys:
      - editedon
  system_settings:
    class: modSystemSetting
    primary: key
    exclude_keys:
      - editedon
    where:
      - 'key:!=': environment
  content_types:
    class: modContentType
    primary: name
  content:
    type: content
    exclude_keys:
      - createdby
      - createdon
      - editedby
      - editedon
  categories:
    class: modCategory
    primary: category
  property_sets:
    class: modPropertySet
    primary: [id,name]
  templates:
    class: modTemplate
    primary: templatename
  template_variables:
    class: modTemplateVar
    primary: name
  template_variables_access:
    class: modTemplateVarTemplate
    primary: [tmplvarid, templateid]
  chunks:
    class: modChunk
    primary: name
    extension: .html
  snippets:
    class: modSnippet
    primary: name
    extension: .php
  plugins:
    class: modPlugin
    primary: name
    extension: .php
  plugin_events:
    class: modPluginEvent
    primary: [pluginid,event]

  users:
    class: modUser
    primary: id
  user_profiles:
    class: modUserProfile
    primary: internalKey
    exclude_keys:
      - sessionid
      - thislogin
      - lastlogin
      - logincount
      - failedloginattempts
  user_groups:
    class: modUserGroup
    primary: id
  user_group_members:
    class: modUserGroupMember
    primary: id
  user_group_roles:
    class: modUserGroupRole
    primary: id

  events:
    class: modEvent
    primary: name
  namespaces:
    class: modNamespace
    primary: name
  mediasources:
    class: modMediaSource
    primary: id
  mediasource_elements:
    class: sources.modMediaSourceElement
    primary: [source, object_class, object, context_key]
  extension_packages:
    class: modExtensionPackage
    primary: namespace

  dashboards:
    class: modDashboard
    primary: [id, name]
  dashboard_widgts:
    class: modDashboardWidget
    primary: id
  dashboard_widget_placement:
    class: modDashboardWidgetPlacement
    primary: [dashboard, widget]

  quickstartbuttons_sets:
    class: qsbSet
    primary: name
    package: quickstartbuttons
  quickstartbuttons_set_usergroups:
    class: qsbSetUserGroup
    primary: [usergoup, set]
  quickstartbuttons_icons:
    class: qsbIcon
    primary: name
  quickstartbuttons_buttons:
    class: qsbButton
    primary: text

  migx_formtab:
    class: migxFormtab
    primary: id
    package: migx
  migx_formtab_field:
    class: migxFormtabField
    primary: id
  migx_config_element:
    class: migxConfigElement
    primary: id
  migx_element:
    class: migxElement
    primary: id
  migx_config:
    class: migxConfig
    primary: id

  cb_fields:
    class: cbField
    primary: name
    package: contentblocks
  cb_layouts:
    class: cbLayout
    primary: name
  cb_templates:
    class: cbTemplate
    primary: name
  cb_defaults:
    class: cbDefault
    primary: id

  collections_settings:
    class: CollectionSetting
    primary: id
    package: collections
  collections_templates:
    class: CollectionTemplate
    primary: [id, name]
  collections_templatecolumns:
    class: CollectionTemplateColumn
    primary: id
  collections_resourcetemplates:
    class: CollectionResourceTemplate
    primary: [resource_template, collection_template]
  collections_selections:
    class: CollectionSelection
    primary: [resource, collection]

packages:
  modx.com:
    service_url: http://rest.modx.com/extras/
    packages:
      - ace
      - breadcrumb
      - collections
      - getresources
      - fastfield
      - getcache
      - getpage
      - translit
      - wayfinder
      - fastfield
      - formit
      - updater
      - locker
      - pthumb
      - redirectoid
      - migx
      - seopro
      - seotab
      - modDevTools
      - ObfuscateEmail-Revo
      - babel
      - xrouting
      - simplesearch

**Comment by Mark-H** [comment]
What happens when you do `Gitify extract --verbose`, what do you see in that log about the items that go wrong?

**Comment by sonicpunk** [comment]
so the context setting that always gets deleted shows this:
- Removed /en.site-start.yaml, no longer exists

**Comment by sonicpunk** [comment]
I checked the database and found that there was an empty row in the table.  I deleted it, and now it works fine.

**Comment by jxarms3** [comment]
my env:
git remote: AWS EC2/GNU/LINUX
git local : windows 10, mysql, using GIT BASH client

I have a site working locally. I have a Gitify workflow working. 
Only hangup is that when ever I do a local Gitify extract, I get 
the dreaded crlf warning for every file in my project.
I have tried to remove this error by:
git config core.autocrlf true/false
   ---- NO EFFECT ------
All files are still marked by this annoying crlf warning rendering 
my workflow unuseable.
Several people tell me to google how git handles lf -> crlf conversion. 
I did, but the common solution has NOT effect.
What do I do?

**Comment by Mark-H** [comment]
This is an issue that was closed **almost 4 years ago**, which also has nothing to do with lf/crlf issues _at all_... was this honestly the best place you could find to post? :/ 

https://help.github.com/articles/dealing-with-line-endings/#platform-all is a pretty good read on the topic. 

For windows the suggest value is `true`, for OS X / Linux it's `input`. You'll need to make sure that's set properly on each environment. You don't mention using the `--global` flag there. Not sure if that's intentional, but I do recommend using global so it's fixed in all your projects on that machine. 

Now, just changing your git config is not sufficient.

If you have existing files or existing history in git, you'll need to deal with it once to set the line endings properly in the files. Again, great resource, this walks you through that: https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings 

As others have told you, this is really not a Gitify specific issue. 

Line endings when dealing with multiple machines suck. Sorry I can't fix that for you.

**Comment by jxarms3** [comment]
Thanks and understand mark
